scikit-bio/scikit-bio

- CHANGELOG.md
- skbio/alignment/_alignment.py
- skbio/alignment/tests/test_alignment.py
- skbio/sequence/_sequence.py
- skbio/sequence/tests/test_sequence.py
Fixed floating point precision bugs in the following methods (and added unit tests):
- ``Alignment.position_frequencies``
- ``Alignment.position_entropies``
- ``Alignment.omit_gap_positions``
- ``Alignment.omit_gap_sequences``
- ``BiologicalSequence.k_word_frequencies``
- ``SequenceCollection.k_word_frequencies``
Also fixed the return types in ``BiologicalSequence.k_word_frequencies`` and ``SequenceCollection.k_word_frequencies`` to be `defaultdict(float)` instead of `defaultdict(int)`.
Removed unnecessary docstrings from `skbio/alignment/tests/test_alignment`.
Fixed a few documentation errors in `skbio/alignment/_alignment.py`.
Fixes #801.
@gregcaporaso can you please review?
> BUG: Fix floating point precision bugs in alignment and sequence frequency calculations

- skbio/alignment/_pairwise.py
The typo mixed up the vertical and horizontal axes in the
traceback matrix at a certain point.
Should resolve #745.
> Fix typo pairwise alignment typo

- CHANGELOG.md
- skbio/util/_misc.py
Deprecated `util.flatten` in favor of standard python solutions.
This is deprecated in 0.2.3-dev. addresses part of #833
> DEP: deprecated `util.flatten`

- CHANGELOG.md
- README.rst
- RELEASE.md
- setup.py
Thanks to http://stackoverflow.com/a/21621689/579416
we can now `pip install scikit-bio` without numpy! It would be great if others could confirm this works on their system on a fresh venv. 
This is very similar to the approach matplotlib uses, just not quite as heavyweight.
> ENH: numpy no longer needed prior to running setup.py

- skbio/__init__.py
Use `#  noqa` to supress an error instead of adding a "spurious
statement" to silence flake8.
> STY: Add `#  noqa` to __init__.py line

- CHANGELOG.md
- skbio/stats/__init__.py
- skbio/stats/evolve/__init__.py
- skbio/stats/evolve/_hommola.py
- skbio/stats/evolve/tests/__init__.py
- skbio/stats/evolve/tests/test_hommola.py
Includes the commits in #557. I made some minor changes, including:
- a few stylistic/readability changes to the code
- docstring updates for clarity
- subpackage restructuring to match latest scikit-bio codebase
- removed sorting of vectors before Pearson calls (will resolve as part of #810 across the codebase)
@tanaes do you mind taking a look at these changes? @ebolyen and/or @gregcaporaso can you also review?
> Hommola cospeciation test (skbio.stats.evolve)

- CHANGELOG.md
- skbio/tree/_tree.py
- skbio/tree/tests/test_tree.py
This fixes an issue where doing `tree1.extend(tree2.children)` or `TreeNode(.... children=tree2.children)` would leave both trees broken.
> [master] BUG: fixed TreeNode.extend when given tree.children; fixes #889

- CHANGELOG.md
- setup.py
- skbio/__init__.py
- skbio/tree/_tree.py
- skbio/tree/tests/test_tree.py
**This is not a duplicate**
This is a PR for 0.2.4, this is a new thing for us so hold on to your pants!
> [0.2.4] BUG: fixed TreeNode.extend when given tree.children; fixes #889

- cookbook/index.html
This is convenient for whiteboards and poster presentations. 
It is a client-side redirect which isn't *awesome*, but it will work.
> WEB: add shortlink to cookbook: http://scikit-bio.org/cookbook

- skbio/diversity/alpha/_lladser.py
This is adds a note that clarifies that `skbio.diversity.alpha.lladser_pe` will not return probabilities less than 1 if the coverages is too low.
> DOC: Update the documentation for lladser_pe

- skbio/alignment/_alignment.py
- skbio/alignment/_pairwise.py
- skbio/io/tests/test_fasta.py
- skbio/sequence/_sequence.py
- skbio/sequence/tests/test_sequence.py
Adds `Sequence.copy(deep=False)` method for performing shallow and deep copies. Adds `Sequence.__copy__`/`__deepcopy__` for interoperability with `copy.copy`/`copy.deepcopy`.
Also updates codebase to use `Sequence.copy` instead of `Sequence._to`.
Addresses part of #949.
@ebolyen can you review?
> ENH: add Sequence.copy method

- CHANGELOG.md
- skbio/stats/distance/_base.py
- skbio/stats/distance/tests/test_base.py
Fixes #943 Pair programmed with @johnchase 
Added test to `test_base.py` for detection of whether large distance matrices were symmetric.
Modified `_base.py` to stop creation of non-symmetric distance matrices and to pass test.
Updated `CHANGELOG.md`
> BUG: Fixed creation of non-symmetric matrices from `randdm`.

- skbio/alignment/_pairwise.py
- skbio/alignment/tests/test_alignment.py
- skbio/alignment/tests/test_ssw.py
- skbio/io/tests/test_base.py
- skbio/io/tests/test_clustal.py
- skbio/io/tests/test_fasta.py
- skbio/io/tests/test_fastq.py
- skbio/io/tests/test_lsmat.py
- skbio/io/tests/test_newick.py
- skbio/io/tests/test_ordination.py
- skbio/io/tests/test_phylip.py
- skbio/io/tests/test_util.py
- skbio/sequence/tests/test_iupac_sequence.py
- skbio/sequence/tests/test_sequence.py
- skbio/stats/distance/tests/test_mantel.py
- skbio/stats/ordination/tests/test_ordination.py
- skbio/util/_misc.py
- skbio/util/tests/test_misc.py
Everything except for I/O-related warnings (those will be fixed in #963). Addresses part of #371.
> MAINT: remove most Py3 warnings

- skbio/io/registry.py
- skbio/io/tests/test_registry.py
Was missing a `seek` call. Test added to detect this issue.
> BUG: fixed sniff for compressed files

- skbio/alignment/_alignment.py
- skbio/alignment/tests/test_alignment.py
fixes this
```python
from skbio.alignment import Alignment
from skbio.sequence import DNA
sequences = [DNA('A--CCGT', id="seq1"),
DNA('AACCGGT', id="seq2")]
a1 = Alignment(sequences)
a1
Out[1]: <Alignment: n=2; mean +/- std length=7.00 +/- 0.00>
a1.score()
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-2-e8aa06dbbab1> in <module>()
----> 1 a1.score()
/home/AMED/michael.panciera/projects/.ngs_mapper/lib/python2.7/site-packages/skbio/alignment/_alignment.py in score(self)
1067 
1068         """
-> 1069         return self._score
1070 
1071     def start_end_positions(self):
AttributeError: 'Alignment' object has no attribute '_score'
```
> Alignment._score not set to None

- skbio/draw/tests/test_distributions.py
- skbio/stats/ordination/tests/test_util.py
- skbio/stats/tests/test_gradient.py
- skbio/tests/test_base.py
Changes:
- `assertEquals` -> `assertEqual`
- `assert_raises_regexp` -> `six.assertRaisesRegex`
- remove 'U' mode from gradient code tests
- make `skbio.draw` `RuntimeWarning` tests more lenient to order of warnings (these were failing for me with a fresh conda install)
> MAINT: misc. updates for better Py3 compatibility

- CHANGELOG.md
- MANIFEST.in
- Makefile
- ci/pip_requirements.txt
- setup.py
Running ``make test`` now invokes [check-manifest](https://github.com/mgedmin/check-manifest) to validate MANIFEST.in.
Fixes #461.
> CI/REL: validate MANIFEST.in using check-manifest package

- CHANGELOG.md
- skbio/alignment/_alignment.py
- skbio/stats/distance/_base.py
- skbio/stats/distance/tests/test_base.py
- skbio/util/_misc.py
- skbio/util/tests/test_misc.py
This serves as a replacement for the `SequenceCollection.distance` method which was the only method on `SequenceCollection` which could not be implemented as a simple list comprehension.
Hopefully we can remove `SequenceCollection` in favor of standard Python types such as `list` and `dict` in the near future.
> DistanceMatrix.from_iterable

- CHANGELOG.md
- skbio/stats/distance/_base.py
Previously, a white border around the heatmap was plotted as matplotlib
does not reduce the plot area to the matrix size. This manually sets the
axis limits to ensure that no border is shown.
> [WIP] Ensure correct DissimilarityMatrix plot dimensions

- CHANGELOG.md
- skbio/alignment/_alignment.py
- skbio/sequence/_iupac_sequence.py
- skbio/sequence/_sequence.py
- skbio/sequence/tests/test_sequence.py
Added `Sequence.frequencies` method for computing character frequencies in a sequence.
Added `Sequence.observed_chars` property for obtaining the set of observed characters in a sequence. 
`Sequence.kmer_frequencies` now returns a `dict` instead of `Counter` or `defaultdict`. See changelog for detailed explanation of this backward-incompatible stable API change.
Fixes #1074. Fixes #1075.
> ENH: add Sequence.frequencies and Sequence.observed_chars

- skbio/alignment/_alignment.py
This corrects a small documentation error.
> The Alignment constructor does not take a validate parameter.

- skbio/__init__.py
- skbio/alignment/__init__.py
- skbio/alignment/_tabular_msa.py
- skbio/alignment/tests/test_tabular_msa.py
- skbio/io/tests/test_registry.py
- skbio/util/__init__.py
- skbio/util/_testing.py
Adds an initial implementation of `TabularMSA` based on the [RFC](https://github.com/biocore/scikit-bio-rfcs/blob/master/active/001-tabular-msa.md). This should be enough of a structure to get other developers involved in implementing the remaining methods in parallel.
Fixes #1081, fixes #1083, fixes #1084, fixes #1085, fixes #1094, fixes #1096, fixes #1099, fixes #1101.
@ebolyen and I pair-programmed parts of this.
To-do:
> initial TabularMSA implementation

- CHANGELOG.md
- skbio/stats/composition.py
- skbio/stats/tests/test_composition.py
This PR does the following 
* Adds 4 new methods `inner`, `ilr`, `ilr_inv` and `clr_inv`
* Clarifies some mathematical details from previous PR
* Cleans up some of the mathjax equations 
This will be the last major PR realized for visualizations.  Like I said before, these methods will complement phylogenetic visualization very nicely.  In addition, these methods are a stepping stone for compositional statistical analysis.
> More Composition analysis methods

- skbio/alignment/_tabular_msa.py
- skbio/alignment/tests/test_tabular_msa.py
- skbio/util/_misc.py
Also made ``TabularMSA.keys`` use ``object`` dtype to prevent lossy conversions.
Fixes #1082, fixes #1095.
> ENH: add TabularMSA.sort, from_dict, and to_dict

- skbio/alignment/_tabular_msa.py
- skbio/alignment/tests/test_tabular_msa.py
Constructor accepts optional `metadata` parameter. Added `TabularMSA.metadata` property with getter, setter, and deleter. Added `TabularMSA.has_metadata`.  Updated `__eq__`/`__ne__` to account for metadata.
Very similar to `Sequence.metadata` implementation. One more class requiring arbitrary metadata will necessitate a mixin.
Fixes #1090.
> ENH: add metadata support to `TabularMSA`

- skbio/io/_iosources.py
- skbio/io/tests/test_util.py
fixes #1103 
Error example:
```python
In [1]: from skbio import DNA
In [2]: DNA.read(['abc'])
---------------------------------------------------------------------------
IOSourceError                             Traceback (most recent call last)
<ipython-input-2-886913a61d43> in <module>()
----> 1 DNA.read(['abc'])
/home/evan/biocore/scikit-bio/skbio/io/registry.pyc in read(cls, file, format, **kwargs)
622         @classmethod
623         def read(cls, file, format=None, **kwargs):
--> 624             return registry.read(file, into=cls, format=format, **kwargs)
625 
626         imports = registry._import_paths(read_formats)
/home/evan/biocore/scikit-bio/skbio/io/registry.pyc in read(self, file, format, into, verify, **kwargs)
495             return (x for x in …
```
> ENH: better error message for PY2 list iosource

- skbio/alignment/_tabular_msa.py
- skbio/io/registry.py
- skbio/sequence/_genetic_code.py
- skbio/sequence/_sequence.py
- skbio/stats/distance/_base.py
- skbio/tree/_tree.py
- skbio/util/_decorator.py
- skbio/util/tests/test_decorator.py
The [descriptor protocol](http://users.rcn.com/python/download/Descriptor.htm) is kewl.
This is very useful for things like `Sequence.concat` where the class which it was called on defines the return type. It used to be possible to say `seq1.concat([seq2, seq3])` but it is ambiguous as to the behaviour (it would only concat seq2 and 3 and cast as the type of seq1, but a future maintainer of such code may not know this, indeed the original author probably didn't either).
> ENH: add classonlymethod decorator

- skbio/_base.py
- skbio/alignment/_tabular_msa.py
- skbio/alignment/tests/test_tabular_msa.py
- skbio/sequence/_sequence.py
- skbio/sequence/tests/test_sequence.py
- skbio/tests/test_base.py
- skbio/util/_testing.py
We were duplicating code on ``Sequence`` and ``TabularMSA`` to support arbitrary metadata. Most, if not all, classes in scikit-bio will eventually support metadata so this refactoring will avoid further code duplication as the project grows.
This commit adds a private mixin ``skbio._base.MetadataMixin`` which centralizes the following metadata logic:
- `metadata` property (getter, setter, deleter)
- `has_metadata` method
- metadata handling in `__init__`
- metadata handling in `__eq__`/`__ne__`
Additionally, a private unit test mixin `skbio.util._testing.MetadataMixinTests` is used to test `MetadataMixin`, `Sequence`, and `TabularMSA`, avoiding redundant unit tests and ensuring that metadata API and behavior is consistent across classes.
> MAINT: use mixin for classes storing metadata

- skbio/alignment/_tabular_msa.py
- skbio/alignment/tests/test_tabular_msa.py
Fixes #1089. Tried out Arrange Act Assert (#1149) for these unit tests. I like it!
This is the first method with an `axis` parameter. The RFC specifies that `'sequence'` and `0` are equivalent, likewise with `'position'` and `1`. However, our notion of `axis` differs from numpy:
```python
In [1]: import numpy as np
In [2]: a = np.array([[1,2,3], [4,5,6]])
In [3]: a
Out[3]:
array([[1, 2, 3],
[4, 5, 6]])
In [4]: a.sum(axis=0)
Out[4]: array([5, 7, 9])
In [5]: a.sum(axis=1)
Out[5]: array([ 6, 15])
In [6]: from skbio import DNA, TabularMSA
In [7]: msa = TabularMSA([DNA('ACG'), DNA('A--')])
In [8]: msa.gap_frequencies(axis=0)
Out[8]: array([0, 2])
In [9]: msa.gap_frequencies(axis=1)
Out[9]: array([0, 1, 1])
```
Is scikit-bio's notion of `axis` correct or should we be matching numpy? Intuitively …
> ENH: add TabularMSA.gap_frequencies

- CHANGELOG.md
- skbio/io/format/tests/test_genbank.py
- skbio/stats/distance/_base.py
- skbio/stats/distance/tests/test_base.py
Changes:
- fix changelog mention
- fix experimental version
- add docstring
- change method name to `to_data_frame`
- more unit tests
Also updated `skbio/io/format/tests/test_genbank.py` to use `six.assertRaisesRegex` instead of deprecated `assertRaisesRegexp`.
> MAINT: some fixes to recent DissimilarityMatrix.to_data_frame method (#1162)

- CHANGELOG.md
- skbio/_base.py
- skbio/alignment/_tabular_msa.py
- skbio/alignment/tests/test_tabular_msa.py
- skbio/sequence/_sequence.py
- skbio/sequence/tests/test_sequence.py
- skbio/tests/test_base.py
- skbio/util/_testing.py
Refactored common code into metadata mixins. Fixes #1158.
@ebolyen shallow copying creates a new list with references to the original sequences. Is that right or should I have it create a new list *and* shallow copy each sequence? See the `TabularMSA` `copy` unit tests for current behavior.
> ENH: add TabularMSA.__copy__/__deepcopy__

- .travis.yml
- doc/source/conf.py
- setup.py
- skbio/alignment/_tabular_msa.py
- skbio/alignment/tests/test_tabular_msa.py
- skbio/util/__init__.py
- skbio/util/_exception.py
- skbio/util/_testing.py
Pair programmed with @jairideout
> ENH: Use pd.Index instead of a numpy array for keys on TabularMSA.

- CHANGELOG.md
- skbio/alignment/_tabular_msa.py
- skbio/alignment/tests/test_tabular_msa.py
- skbio/sequence/_dna.py
- skbio/sequence/_iupac_sequence.py
- skbio/sequence/_protein.py
- skbio/sequence/_rna.py
- skbio/sequence/tests/test_iupac_sequence.py
Contains commits in #1129. Fixes #1091.
To-do:
> ENH: TabularMSA.consensus

- skbio/alignment/_tabular_msa.py
- skbio/alignment/tests/test_tabular_msa.py
Added `TabularMSA.extend` and copy constructor.
`append` `label` parameter name changed to `index` for consistency with
constructor and `extend`.
Internal refactoring: constructor and `append` now use `extend` to reduce code
duplication.
Fixes #1097.
> ENH: TabularMSA.extend, copy constructor

- skbio/alignment/_alignment.py
- skbio/alignment/_tabular_msa.py
- skbio/io/__init__.py
- skbio/io/_exception.py
- skbio/io/format/_base.py
- skbio/io/format/clustal.py
- skbio/io/format/fasta.py
- skbio/io/format/fastq.py
- skbio/io/format/phylip.py
- skbio/io/format/tests/data/phylip_variable_length_ids
- skbio/io/format/tests/test_clustal.py
- skbio/io/format/tests/test_fasta.py
- skbio/io/format/tests/test_fastq.py
- skbio/io/format/tests/test_phylip.py
Removed `Alignment` from I/O. Updated I/O format docs as necessary. Fixes #1197.
> ENH: hook `TabularMSA` up to `skbio.io`

- skbio/alignment/_tabular_msa.py
- skbio/alignment/tests/test_tabular_msa.py
Also made some additions and general improvements to the docs throughout, including replacing "alphabet-aware scikit-bio sequence object" with "IUPACSequence".
Fixes #1206.
> DOC: update TabularMSA doctests to use repr

- RELEASE.md
- ci/pip_requirements.txt
- setup.py
Two changes: 
* ``conda build`` doesn't like the "extras" syntax, so this will save us from having to edit the ``meta.yaml`` that gets created by ``conda skeleton``
* update release notes document
> prep for conda releases

- CHANGELOG.md
- skbio/_base.py
Tested in sphinx docs and interactive IPython session. Here's the example that resulted in creation of #1210:
All better now...
> fixes ordination plot legends

- doc/source/_static/copybutton.js
JQuery deprecated `toggle` in 1.9 and replaced it with an identical function that controls visibility and animation instead. So not only did the click event stop working, calling toggle made them all disappear!
> WEB: update copybutton.js for JQuery 1.9

- ci/pip_requirements.txt
- skbio/diversity/alpha/_lladser.py
- skbio/io/format/fasta.py
- skbio/io/format/fastq.py
- skbio/io/format/tests/test_fasta.py
- skbio/io/registry.py
- skbio/sequence/tests/test_sequence.py
- skbio/stats/power.py
- skbio/stats/tests/test_gradient.py
- skbio/tree/_tree.py
- skbio/util/__init__.py
- skbio/util/_decorator.py
- skbio/util/_misc.py
- skbio/util/_testing.py
- skbio/util/_warning.py
- skbio/util/tests/test_decorator.py
- skbio/util/tests/test_misc.py
This PR does 3 things:
- Drops the version of HTTPretty because their latest release has a syntax error in Py3
- Subclass all scikit-bio warnings from `SkbioWarning` this allows us to filter only those warnings in the test. Ideally this will make real warnings more noticeable.
- Fix a bunch of warnings throughout the codebase so things don't fall apart come `3.6` or new `pandas`/`scipy` release. 
@gregcaporaso could you review? The `HTTPretty` part is blocking #1242
> Warning fixes

- CHANGELOG.md
Put in the normal categories.
Moved `multiplicative_replacement` note.
Added note about common warning subclass.
> DOC: fixed changelog

- CHANGELOG.md
- skbio/io/format/genbank.py
- skbio/io/format/tests/test_genbank.py
When reading GenBank files, the date field of the LOCUS line is no longer
parsed into a `datetime.datetime` object and is left as a string. When writing
GenBank files, the locus date metadata is expected to be a string instead of a
`datetime.datetime` object.
Fixes #1153.
> Fixes #1153

- skbio/stats/composition.py
- skbio/stats/ordination/tests/test_redundancy_analysis.py
- skbio/util/_testing.py
Closes #1267.
Like the other ordination functions, directionality has to be "ignored" when comparing results. I can't reproduce the sign changes in #1267, so please @jairideout let me know if this works in your end :)
> Deal with different lapacks

- doc/source/_static/style.css
fixes #1268 
Point 2. seems to have been a transient issue with some version of sphinx/sphinx-bootstrap-theme. It appears to be resolved in the latest versions of both.
> WEB: fixed style of signatures

- CHANGELOG.md
- skbio/sequence/__init__.py
- skbio/sequence/_sequence.py
- skbio/sequence/distance.py
- skbio/sequence/tests/test_distance.py
- skbio/sequence/tests/test_sequence.py
- skbio/stats/distance/tests/test_base.py
Made the following changes:
- scikit-bio `Sequence` objects have better compatibility with numpy. For example, calling `np.asarray(sequence)` now converts the sequence to a numpy array of characters (the same as calling `sequence.values`).
- Added `skbio.sequence.distance` subpackage for computing distances between scikit-bio `Sequence` objects. This plugs into `Sequence.distance` and `DistanceMatrix.from_iterable`.
- Fixed bug when using `Sequence.distance` or `DistanceMatrix.from_iterable` to compute distances between `Sequence` objects with differing `metadata`/`positional_metadata` and passing `metric=scipy.spatial.distance.hamming`
- Fixed performance bug when computing Hamming distances between `Sequence` objects in `DistanceMatrix.from_iterable`
Fixes #1254. Fixes #1250. Addresses …
> ENH/BUG/PERF: improvements to Sequence distance calculations

- CHANGELOG.md
- skbio/tree/_tree.py
- skbio/tree/tests/test_tree.py
This PR is to address https://github.com/biocore/scikit-bio/issues/896
Some of the analyses I've been doing has required strictly bifurcating trees, so this method 
1. Introduces additional internal nodes to ensure that all the internal nodes have exactly 2 children
2. Removes nodes that have exactly one child (if `remove_singles=True`)
The order in which these internal nodes are injected or how the single child nodes are removed are a little arbitrary at the moment.
Todo
> Multifurcating tree to Bifurcating tree

- CHANGELOG.md
- skbio/alignment/_tabular_msa.py
- skbio/alignment/tests/test_tabular_msa.py
- skbio/io/format/stockholm.py
- skbio/io/format/tests/test_stockholm.py
- skbio/metadata/_mixin.py
- skbio/metadata/_repr.py
- skbio/metadata/_testing.py
- skbio/metadata/tests/test_mixin.py
- skbio/sequence/_dna.py
- skbio/sequence/_genetic_code.py
- skbio/sequence/_grammared_sequence.py
- skbio/sequence/_nucleotide_mixin.py
- skbio/sequence/_rna.py
- skbio/sequence/_sequence.py
- skbio/sequence/tests/test_grammared_sequence.py
- skbio/sequence/tests/test_sequence.py
Removed memory optimizations for storing empty `metadata` and `positional_metadata`, currently on `Sequence` and `TabularMSA`.
Previously, empty metadata was stored internally as `None`, and an empty metadata representation (e.g., `{}` or `pd.DataFrame(index=range(axis_len))` was created and stored on the object when `.metadata` or `.positional_metadata` properties were accessed for the first time.
While this optimization resulted in some memory savings, its implementation is not sustainable because scikit-bio devs must remember to use `has_metadata` or `has_positional_metadata` to handle empty metadata efficiently, otherwise any memory savings are lost. Every routine interacting with metadata needed a unit test ensuring empty metadata is handled efficiently, and worse, these tests had to …
> MAINT: remove empty metadata optimizations

- CHANGELOG.md
- skbio/io/format/stockholm.py
- skbio/io/format/tests/test_stockholm.py
- skbio/sequence/tests/test_grammared_sequence.py
Fixes #1327
Additionally fixes minor bug in tests with new error message. (The second test could be catching the new error message instead of its error message).
Also contains fix of `import` statement in `skbio.sequence.tests.test_grammared_sequence`
> Expands error message in `skbio.io.format.stockholm`

- CHANGELOG.md
- ci/conda_requirements.txt
- setup.py
- skbio/alignment/_tabular_msa.py
- skbio/alignment/tests/test_tabular_msa.py
- skbio/io/format/blast6.py
- skbio/io/format/blast7.py
- skbio/io/format/phylip.py
- skbio/metadata/_mixin.py
- skbio/metadata/_testing.py
- skbio/sequence/_sequence.py
- skbio/sequence/tests/test_sequence.py
- skbio/stats/distance/_base.py
- skbio/stats/tests/test_gradient.py
Fixes #1308. scikit-bio now depends on pandas >= 0.18.0.
Added support for `pandas.RangeIndex`, lowering the memory footprint of default integer index objects. `Sequence.positional_metadata` and `TabularMSA.positional_metadata` now use `pd.RangeIndex` as the positional metadata index. `TabularMSA` now uses `pd.RangeIndex` as the default index.  Usage of `pd.RangeIndex` over the previous `pd.Int64Index` [should be transparent](http://pandas.pydata.org/pandas-docs/version/0.18.0/whatsnew.html#range-index), so these changes should be non-breaking to users.
Added `reset_index=False` parameter to `TabularMSA.append` and `TabularMSA.extend` for resetting the MSA's index to the default index after appending/extending. `TabularMSA.append` and `TabularMSA.extend` now require one of `minter`, …
> ENH: pandas 0.18.0 support

- CHANGELOG.md
- skbio/diversity/__init__.py
- skbio/diversity/_driver.py
- skbio/diversity/tests/test_driver.py
Addresses #1221.
Specific questions:
* ~~Validation was pushed into `_partial_pw` to not clog `beta_diversity`, is this preferred?~~
* ~~The mechanism for resolving string forms of metrics (e.g., `"euclidean"`) is not [exposed](https://github.com/scipy/scipy/blob/v0.17.0/scipy/spatial/distance.py#L1249) in scipy's `pdist` making it difficult to support scipy-native metrics. Is this a blocker?~~ The method resolution in scipy makes a large number of internal assumptions, and likely requires a fairly substantial PR to scipy in order to even expose `euclidean`. As such, I'd prefer to merge this with support only for skbio metrics and passed in callables, as there is a near-term need for this functionality for UniFrac.  
* ~~The condensed form of the matrix is returned, but it isn't clear if …
> Partial pairwise calculation for beta diversity.

- skbio/alignment/_tabular_msa.py
- skbio/alignment/tests/test_tabular_msa.py
TabularMSA was already unhashable because it defines an `__eq__` without `__hash__`. This commit makes an explicit statement that it is unhashable and includes some unit tests.
> MAINT: explicitly make TabularMSA unhashable

- CHANGELOG.md
- benchmarks/benchmarks.py
- skbio/_base.py
- skbio/alignment/_indexing.py
- skbio/alignment/_tabular_msa.py
- skbio/io/format/stockholm.py
- skbio/metadata/_mixin.py
- skbio/metadata/_repr.py
- skbio/metadata/_testing.py
- skbio/sequence/_dna.py
- skbio/sequence/_genetic_code.py
- skbio/sequence/_grammared_sequence.py
- skbio/sequence/_nucleotide_mixin.py
- skbio/sequence/_rna.py
- skbio/sequence/_sequence.py
- skbio/sequence/tests/test_sequence.py
Fixes #1361 by reinstating the empty/missing metadata optimizations that were removed in #1321.
This is not a commit revert because upstream changes have happened since #1321, causing many merge conflicts. We also want to keep some of the changes in #1321 and discard others, so a manual revert was necessary.
The unit tests testing private state to ensure performance have not been reinstated, as this didn't scale (from a development/codebase perspective) and was fragile to implementation details. Now, private state unit tests exist only for the metadata mixin classes, where that private state is defined. Instead of writing private state unit tests for performance, users and developers are encouraged to submit ASV benchmarks if a method is determined to have suboptimal performance when …
> BUG: fix performance regression by reinstating empty metadata optimizations

- CHANGELOG.md
- skbio/alignment/_pairwise.py
- skbio/alignment/tests/test_pairwise.py
Docs in `skbio.alignment` were unaffected. 
Negligible performance change (actually improved because I added `validate=False` which more than offsets the cost of checking for metadata)
> ENH: Pairwise aligners propagate seq `metadata`

- CHANGELOG.md
- skbio/tree/_tree.py
- skbio/tree/tests/test_tree.py
Found a bug when using `TreeNode.shear` where `TreeNode.prune` could not handle a resulting subtree in which the root was not included. `TreeNode.prune` is called implicitly by `shear`.
> Treenode prune bug

- CHANGELOG.md
- skbio/stats/distance/_base.py
- skbio/stats/distance/tests/test_base.py
Moves `from_iterable` definition from `DistanceMatrix` to `DissimilarityMatrix` (`DistanceMatrix` inherits from `DissimilarityMatrix`).
Copied existing `DistanceMatrix` `from_iterable` tests.
Fixes #1343.
Thanks!
> ENH: Add DissimiliarityMatrix.from_iterable

- CHANGELOG.md
- setup.py
Closes #1407.
Based on a StackOverflow answer: http://stackoverflow.com/a/14657667/1951857
Sorry that I haven't followed all of the guidelines in `CONTRIBUTING.md`, but this is a pretty quick fix.
It's possible that this the error being fixed is Python3 specific.  This has not been fully tested.
> Fix an error on `pip install`

- setup.py
I was able to build a bdist_wheel on Win10 64 and it didn't crash when trying to use the ssw extension (https://github.com/biocore/scikit-bio/issues/702#issuecomment-60054711).
```
Python 3.5.2 (v3.5.2:4def2a2901a5, Jun 25 2016, 22:18:55) [MSC v.1900 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import skbio
>>> from skbio.alignment._ssw_wrapper import StripedSmithWaterman as ssw
>>> x = ssw('AATTTNGNTTTANTTNGTA')
>>> x('AATTGNTNANTNGNTAATNGT')
{
'optimal_alignment_score': 10,
'suboptimal_alignment_score': 0,
'query_begin': 9,
'query_end': 18,
'target_begin': 6,
'target_end_optimal': 15,
'target_end_suboptimal': 0,
'cigar': '10M',
'query_sequence': 'AATTTNGNTTTANTTNGTA',
'target_sequence': 'AATTGNTNANTNGNTAATNGT'
}
```
> Fix compiler error on Windows

- skbio/__init__.py
Fixes https://github.com/biocore/scikit-bio/issues/1309. the following example no longer fails with an `AttributeError`, all other sub-modules are already accessible:
```
import skbio
skbio.diversity
skbio.stats.evolve
```
Not sure if we want to add to `__all__`, since wildcard imports ( from skbio import * ) should be avoided (PEP8).
> Include subpackages in __init__.py #1309

- .travis.yml
- ci/matplotlibrc
The newest versions of qt and pyqt installed with conda are incompatible with matplotlib. Force a non-Qt backend to get Travis builds passing again.
> CI: force matplotlib Agg backend

- skbio/stats/power.py
- skbio/stats/tests/test_power.py
cleans up code (slightly)
corrects for pandas data typing and improves testing based on arrays
rather than lists
addresses #1436; this looks like a broken test following pandas compatibility
...I did have a bunch of test break associated with `skbio.io.format.tests.test_blast7.TestBlast7Reader`
> fixes issue with paired test

- skbio/metadata/_intersection.c
- skbio/metadata/_intersection.pyx
- skbio/metadata/tests/test_intersection.py
This addresses #1448. The bug is that I need to change the greater/less-than signs to greater/less-than-or-equal-to sign to search for left/right subtree.
The fact that tests passes in some environment was confusing and misleading. The reason for that behavior is that OSX and linux starts with different interval nodes to search intersection. If it started with the lucky node (as in OSX), it would find the expected nodes; if it is not (as in some cases in linux), it ignored left or right subtree and returned empty.
> fix a bug in _intersection.pyx

- RELEASE.md
Updated the release document to use conda instead of virtualenv. Added instructions for updating API stability decorator versions and removing deprecated functionality. Made other general improvements to the doc, including better CLI commands and clearer ordering of steps in the release process.
These new instructions roughly reflect the steps taken to build scikit-bio 0.5.1.
Fixes #1238.
Note: the diff is hard to follow. I recommend reading through the rendered doc.
> DOC: update release document

- skbio/alignment/tests/test_pairwise.py
- skbio/alignment/tests/test_tabular_msa.py
- skbio/io/format/tests/test_clustal.py
- skbio/io/format/tests/test_fasta.py
- skbio/io/format/tests/test_fastq.py
During `make test` in a development environment, `./checklist.py` returns a 1 status code and invalidate test phase. By importing modules from main modules, eg:
```    
-from skbio.util._decorator import classproperty, overrides
+from skbio.util import classproperty
+from skbio.util._decorator import overrides
````    
./checklist.py returns 0, and tests are OK
> fixing ./checklist.py imports - fixes #1481

- CHANGELOG.md
- skbio/tree/_nj.py
----------
Hello,
This pull request references issue #431 by modifying the `_compute_q` function to use CPU vector operations to achieve a significant speedup. I timed the code using `%timeit`, whereby the original function resulted in: `100 loops, best of 3: 181 ms per loop` and the vectorized function resulted in: `100 loops, best of 3: 568 µs per loop`. In addition, for a 10x larger distance matrix, the original code is still running in the time it took me to modify the code and create this pull request. Running `make test` appears to pass without …
> vectorized _compute_q (issue #431)

- CHANGELOG.md
- skbio/tree/_nj.py
- skbio/tree/tests/test_nj.py
------
Hello,
This pull request references issue #431 by modifying `_lowest_index` and `_compute_collapsed_dm` to avoid item-by-item testing or copying. In the case of `_lowest_index`, the item-by-item checking is replaced with a call to `amin` on the dense form of the distance matrix data followed by point selection to produce the same behavior as point-by-point ordered checking. In the case of `_compute_collapsed_dm`, the existing `DistanceMatrix` data which can be re-used is copied as a single block before point-by-point computation of the …
> more speedups to `nj` (issue #431)

- CHANGELOG.md
- ci/conda_requirements.txt
- ci/pip_requirements.txt
- doc/source/conf.py
- setup.py
- skbio/alignment/tests/test_pairwise.py
- skbio/diversity/tests/test_driver.py
- skbio/io/format/genbank.py
- skbio/io/tests/test_util.py
- skbio/metadata/tests/test_intersection.py
- skbio/metadata/tests/test_interval.py
- skbio/sequence/tests/test_nucleotide_sequences.py
Made the following changes to fix build/test failures:
- scikit-bio now depends on `numpy >= 1.9.2, < 1.14.0` for compatibility with Python 3.4, 3.5, and 3.6 and the available numpy conda packages in `defaults` and `conda-forge` channels.
- Use latest Sphinx release (1.6) instead of Sphinx master branch.
- Fix flake8 errors related to updated flake8 package.
- Fix unit test for beta_diversity error message to work across supported Python 3 versions.
> MAINT: various changes to fix build/test failures

- ci/pip_requirements.txt
numpydoc 0.8.0 throws the following, restricting to numpydoc < 0.8.0.
```bash
Traceback (most recent call last):
File
"/Users/mcdonadt/miniconda3/envs/py36-skbio/lib/python3.6/site-packages/sphinx/config.py",
line 161, in __init__
execfile_(filename, config)
File
"/Users/mcdonadt/miniconda3/envs/py36-skbio/lib/python3.6/site-packages/sphinx/util/pycompat.py",
line 150, in execfile_
exec_(code, _globals)
File "conf.py", line 73, in <module>
import numpydoc
ModuleNotFoundError: No module named 'numpydoc'
```
> BLD/TST: gating numpydoc, 0.8.0 throws the following exception:

- CHANGELOG.md
- skbio/tree/_tree.py
- skbio/tree/tests/test_tree.py
***
Hello @wasade @RNAer @mortonjt (and @antgonza ) , thanks for reviewing my first PR to scikit-bio and merged it. Here is my second PR, which is slightly more complex. The `unpack` method removes an internal node and regrafts its children to its parent. The `unpack_by_func` method does this in a batch mode. These functions are useful when the user wants to unpack short and low-support nodes from a tree. The code was also [reviewed](https://github.com/biocore/horizomer/pull/75) by @sjanssen2 , @tanaes and @mortonjt , and was presented and discussed …
> Added methods unpack and unpack_by_func to TreeNode

- CHANGELOG.md
- skbio/diversity/_util.py
- skbio/diversity/tests/test_util.py
This addresses both #1580 and #1581.  Note that by removing this type check, this will open the doors for other normalization techniques (i.e. total sum scaling) that are floating-point valued.
> FIX: removing integer type check in diversity calculations

- skbio/alignment/_indexing.py
Fixes a few warnings in the test about `Index.get_duplicates()` being deprecated.
This works with pandas 0.23.0, so it should be ok -- the oldest version of pandas that scikit-bio supports is 0.23, per setup.py.
> Replace TabularMSALoc use of Index.get_duplicates

- skbio/alignment/_indexing.py
- skbio/alignment/_tabular_msa.py
- skbio/alignment/tests/test_tabular_msa.py
- skbio/diversity/__init__.py
- skbio/io/format/_base.py
- skbio/io/format/tests/test_stockholm.py
- skbio/sequence/_grammared_sequence.py
- skbio/sequence/_sequence.py
- skbio/sequence/tests/test_nucleotide_sequences.py
- skbio/sequence/tests/test_sequence.py
- skbio/stats/distance/_mantel.py
- skbio/stats/ordination/_canonical_correspondence_analysis.py
- skbio/stats/ordination/_redundancy_analysis.py
- Use scipy.special.comb instead of scipy.misc.comb
- fromstring -> frombuffer + ascii encode
- .as_matrix -> .values
- more dict order sensitivity
- avoid deprecation on pd.concat by using sort=True
- replace TabularMSA use of Index.get_duplicates
- removing pandas from_list everywhere
> MAINT: fixes many deprecation warnings

- .travis.yml
- ci/pip_requirements.txt
- doc/README.md
- doc/source/_static/copybutton.js
- doc/source/_templates/autosummary/class.rst
- doc/source/conf.py
- skbio/diversity/alpha/__init__.py
- skbio/diversity/beta/__init__.py
- skbio/io/__init__.py
- skbio/io/registry.py
- skbio/sequence/_dna.py
- skbio/sequence/_grammared_sequence.py
- skbio/sequence/_nucleotide_mixin.py
- skbio/sequence/_protein.py
- skbio/sequence/_rna.py
- skbio/sequence/_sequence.py
- skbio/sequence/distance.py
- skbio/stats/composition.py
- skbio/stats/distance/__init__.py
- skbio/stats/distance/_permdisp.py
- skbio/stats/evolve/__init__.py
- skbio/stats/gradient.py
- skbio/stats/ordination/__init__.py
- skbio/stats/ordination/_ordination_results.py
- skbio/stats/power.py
- skbio/tree/_tree.py
We did a couple of things here:
- Got rid of numpydoc, we are now using napoleon (shipped with the core sphinx distro).
- Cleaned up the building process (specifically conf.py).
- Cleaned up the generated files to not live under `generated/generated`.
- Fix the copybutton on the code blocks to hide the prompt `>>>`.
- Update the class documentation formatting.
Co-authored with @ebolyen
> Update documentation building to use napoleon

- skbio/sequence/_sequence.py
---
fixes #1648 
Turns out the issue was embarrassingly simple: since numpy does not own the backing bytes of string/byte literals, neither do we. This change corrects that in the constructor.
There are very really no situations where skbio will assume byte ownership except for one branch that I don't remember the cause of. We may want to think about either removing these semantics entirely, _or_ add an API to indicate the skbio may mutate the buffer (passing ownership of a numpy array you've created yourself onwards to skbio, assuming the ndarray …
> BUG: fix ownership for byte/string literals

- CHANGELOG.md
- skbio/stats/distance/_base.py
- skbio/stats/distance/tests/test_base.py
- skbio/stats/distance/tests/test_mantel.py
- skbio/stats/evolve/_hommola.py
- skbio/stats/ordination/_principal_coordinate_analysis.py
- skbio/stats/power.py
This pull request adds in `.within` and `.between` methods to the `DissimilarityMatrix` object, and expressing the data as a `pd.DataFrame`. These methods provide a standard way for obtaining within and between group distances, a common operation for beta-diversity derived distance matrices.
> Within and between distance API methods for the DissimilarityMatrix object

- CHANGELOG.md
- MANIFEST.in
- pyproject.toml
This specifies numpy as a build dependency so that the package can be installed with pip without the user having to first manually install numpy, partially solving https://github.com/biocore/scikit-bio/issues/1671. Unfortunately, hdmedians has the same issue.
> Add numpy as build dependency in pyproject.toml

- .travis.yml
- CHANGELOG.md
- ci/conda_requirements.txt
- skbio/alignment/_tabular_msa.py
- skbio/diversity/_util.py
- skbio/io/tests/test_registry.py
- skbio/stats/distance/_base.py
- skbio/stats/distance/tests/test_base.py
- skbio/stats/ordination/tests/test_ordination_results.py
We observed a Mantel R^2 of 0.9999 between float32 and float64 results with weighted UniFrac when applied to the EMP dataset (~27k samples). This observation arose from a recent GPU adaption of [UniFrac](https://arxiv.org/abs/2005.05826) when testing for a performance difference when computing float32 and float64. We're now producing float32 matrices from UniFrac as it's appreciably faster, however the `DissimilarityMatrix` object at the moment requires double precision. This PR allows `DissimilarityMatrix` to both support float32, and to avoid an implicit copy that would occur if passing in float32 data. 
The implicit copy is important to avoid for large matrices to keep resident memory low.  
**Note:** …
> Allow `DissimilarityMatrix` to use `np.float32`

- skbio/stats/distance/_cutils.c
- skbio/stats/distance/_cutils.pyx
- skbio/stats/ordination/_cutils.c
- skbio/stats/ordination/_cutils.pyx
Properly tune the tilling in f_matrix_inplace_cy and is_symmetric_and_hollow_cy.
It was too big and was trashing the L1 cache.
Addresses issue #1762 and builds on #1748.
For a 100k*100k matrix on a 16 core Xeon Gold 6242 we go from
center_matrix 50s to 5s
DistanceMatrix validation from 54s to 3.8s
> Properly tune the tilling #1762

- CHANGELOG.md
- skbio/stats/distance/_permdisp.py
- skbio/stats/distance/tests/test_permdisp.py
Add support for PCoA method and number_of_dimensions to permdisp.
Details in issue #1769
> Add PCoA method support to permdisp - Issue #1769

- CHANGELOG.md
- Makefile
- ci/conda_requirements.txt
- setup.py
- skbio/diversity/_driver.py
- skbio/diversity/_util.py
- skbio/diversity/tests/test_driver.py
- skbio/diversity/tests/test_util.py
scikit-learn has been removed as a dependency. This was a fairly heavy-weight dependency that was providing minor functionality to scikit-bio. The critical components have been implemented in scikit-bio directly. 
The other change that comes along with this is that three beta diversity metrics that were provided by sklearn are no longer available. These are `wminkowski`, `nan_euclidean`, and `haversine`. On testing, `wminkowski` and `haversine` did not work through `skbio.diversity.beta_diversity` (or `sklearn.metrics.pairwise_distances`). The former was deprecated in favor of calling `minkowski` with a vector of weights provided as kwarg `w` , and the latter does not work with data of this shape. `nan_euclidean` can still be accessed from scikit-learn directly if a user installs …
> remove scikit-learn dependency 

- doc/source/_templates/autosummary/module.rst
Docs now look the same as the last release, and even work with the current sphinx alpha release to boot.
> DOC: update autosummary templates to avoid double entry

- CHANGELOG.md
- skbio/alignment/_pairwise.py
Addresses #1814. 
Example: 
```python
In [1]: import warnings
In [2]: warnings.simplefilter('default')
In [3]: from skbio import DNA
In [4]: from skbio.alignment import local_pairwise_align_ssw
In [5]: local_pairwise_align_ssw(DNA('ACCGTTGAC'), DNA('CAGGTAGT'))
/Users/gregcaporaso/Documents/code/scikit-bio/skbio/util/_decorator.py:254: DeprecationWarning: local_pairwise_align_ssw is deprecated as of scikit-bio version 0.5.8, and will be removed in version 0.6.0. This will be removed or replaced, in favor of more general-purpose performant aligners. Additional details at https://github.com/biocore/scikit-bio/issues/1814
...
```
> deprecate local_pairwise_align_ssw

- CHANGELOG.md
- skbio/util/_decorator.py
This PR updated the string formatting of the `_state_decorator` class from modulo based formatting to more current f-string formatting. This is the beginning of what will be an ongoing effort to modernize the skbio package. 
> Updated _state_decorator string formatting

- CHANGELOG.md
- skbio/alignment/_indexing.py
- skbio/io/format/stockholm.py
Since `slice` objects are hashable in Python 3.12, `pd.MultiIndex` no longer raises a `TypeError` when its `__contains__` method is called with a `slice` object. Instead, Pandas checks whether the argument is a `slice` and raises an `InvalidIndexError` instead. This change catches such errors in addition to `TypeError` to fix slicing for `TabularMSALoc`.
Python 3.12 also changes the `repr` for `OrderedDict`. This change revises the docstring for skbio.io.format.stockholm to display `OrderedDict` objects as lists of items so that we get the same results on Python 3.12 as we do on earlier versions of Python.
fixes #1926 
---
**Note:** [REVIEWING.md](https://github.com/scikit-bio/scikit-bio/blob/master/REVIEWING.md) may also be helpful to see some of …
> Fix TabularMSALoc slicing on Python 3.12 and change documentation for skbio.io.format.stockholm to be independent of OrderedDict repr

- ci/requirements.test.txt
- skbio/io/tests/test_util.py
From issue #1919. This PR replaces [HTTPretty](https://github.com/gabrielfalcao/HTTPretty) with [Responses](https://github.com/getsentry/responses) in our unit tests. Responses is a more modern and actively developed package for mocking out the Python Requests library. 
**Note:** [REVIEWING.md](https://github.com/scikit-bio/scikit-bio/blob/master/REVIEWING.md) may also be helpful to see some of the things code reviewers will be verifying when reviewing your pull request.
> Replacing HTTPretty with Responses

- web/contribute.rst
This PR adds documentation regarding running Ruff and pre-commit if changes have been made before their installation.
> Add run --all-files option to pre-commit documentation

- skbio/sequence/_dna.py
- skbio/sequence/_protein.py
- skbio/sequence/_rna.py
Fixes text formatting issues in `Sequence` subpackages.
This:
Becomes this:
> Fix text formatting for tables in sequence subpackages

- skbio/alignment/tests/test_tabular_msa.py
- skbio/sequence/tests/test_sequence.py
- skbio/stats/ordination/tests/test_ordination_results.py
- skbio/stats/tests/test_subsample.py
- web/devdoc/code_guide.rst
@mataton This is a simple quick fix. `nose` was a popular testing framework for Python, however scikit-bio has long adopted `pytest` together with the built-ib `unittest` framework, and dropped `nose`. There were still some left overs of `nose` which could cause errors in some situations. I just removed them.
Note: [This document](https://scikit.bio/devdoc/review.html) may also be helpful to see some of the things code reviewers will be verifying …
> Removed remnants of nosetests

- CHANGELOG.md
- skbio/diversity/__init__.py
- skbio/diversity/_block.py
- skbio/diversity/_driver.py
- skbio/diversity/_phylogenetic.pyx
- skbio/diversity/_util.py
- skbio/diversity/alpha/_ace.py
- skbio/diversity/alpha/_base.py
- skbio/diversity/alpha/_chao1.py
- skbio/diversity/alpha/_lladser.py
- skbio/diversity/alpha/_pd.py
- skbio/diversity/alpha/tests/test_ace.py
- skbio/diversity/alpha/tests/test_base.py
- skbio/diversity/alpha/tests/test_lladser.py
- skbio/diversity/alpha/tests/test_pd.py
- skbio/diversity/beta/_unifrac.py
- skbio/diversity/beta/tests/test_unifrac.py
- skbio/diversity/tests/test_block.py
- skbio/diversity/tests/test_driver.py
- skbio/diversity/tests/test_util.py
- skbio/stats/composition.py
- skbio/tree/_nj.py
- skbio/tree/tests/test_tree.py
- web/devdoc/code_guide.rst
This PR removes the outdated term "OTU" from both documentation and code, and replaces it with the more generic term "taxon". As a consequence, the parameter `otu_ids` now becomes `taxa`. This affects `faith_pd`, `phydiv`, `unweighted_unifrac` and `weighted_unifrac`. The parameter `otu_ids` is kept as an alias of `taxa`, such that existing code that uses these functions will not break. A deprecation warning is displayed in the documentation.
Note: …
> Deprecated "OTU" in favor of "taxon"

- skbio/io/format/sample_metadata.py
Simple fix for incorrectly rendered bullet point lists in the `sample_metadata` documentation. Without the space added, the first item of the bullet list would render on the same line as the category for that list.
Before:
Upon merge:
> Fix doc rendering issues in sample_metadata

- CHANGELOG.md
- skbio/stats/composition.py
- skbio/stats/tests/test_composition.py
This PR touches up the `skbio.stats.composition` module to improve its usability.
Main changes (following discussion with @mortonjt):
- Abbreviated `multiplicative_replacement` as `multi_replace` for simplicity. The old function is kept as an alias for backward compatibility.
- Implemented the Benjamini-Hochberg method for FDR correction, in addition to the existing Holm-Bonferroni method.
- Added a parameter `p_adjust` for both `ancom` and `dirmult_ttest`.
- The word `p_adjust` is consistent with R, statsmodels, and QIIME2's ANCOM-BC plugin.
- The value of `p_adjust` can be None, "holm", "holm-bonferroni", "bh", "fdr_bh", "benjamini-hochberg" (case insensitive). This is to ensure compatibility with statsmodels' `multipletests`, which we may adopt in the future.
- The original parameter …
> House keeping works for the composition module

- skbio/diversity/tests/test_driver.py
- skbio/io/format/fasta.py
- skbio/io/format/tests/test_taxdump.py
- skbio/stats/distance/tests/test_bioenv.py
- skbio/stats/distance/tests/test_mantel.py
- skbio/util/_testing.py
This PR fixes underlying issues with the way Pandas handles `int`s on Windows.
> Fix default int types for Pandas DataFrame and Series

- skbio/stats/_subsample.py
This patch skips two unnecessary copies of the counts vector.
> Avoid copying data in subsample_counts

- skbio/alignment/_path.py
- skbio/diversity/__init__.py
- skbio/sequence/_nucleotide_mixin.py
- skbio/stats/composition.py
- skbio/stats/power.py
- skbio/tree/_tree.py
This PR fixes doctests for Windows compatibility. Simple implementation of `doctest: +ELLIPSIS` was used to ignore `dtype` differences across platforms.
> Fix doctests on Windows

- skbio/metadata/_testing.py
- skbio/metadata/io.py
- skbio/metadata/tests/test_io.py
- skbio/stats/distance/_permdisp.py
- skbio/stats/gradient.py
- skbio/stats/ordination/tests/test_redundancy_analysis.py
This PR contains three commits which fix about 3500 warnings.  
```
============================================================= 
3000 passed, 4093 warnings in 42.13s 
=============================================================
```
```
============================================================= 
3000 passed, 521 warnings in 39.72s 
=============================================================
```
---
1) The warning was raised because `pkg_resources` has been deprecated. After confirming that `pkg_resources` is not utilized within the codebase, I have removed the import to resolve the warning.
``` 
../skbio/metadata/tests/test_io.py:3
/Users/aryank/Developer/scikit-bio/skbio/metadata/tests/test_io.py:3: DeprecationWarning: pkg_resources is deprecated as an API. See …
```
> Resolved Warnings 

- skbio/diversity/_phylogenetic.pyx
- skbio/diversity/beta/_unifrac.py
- skbio/stats/distance/_mantel.py
- skbio/stats/distance/_utils.py
- skbio/stats/distance/tests/test_mantel.py
This PR ensures backwards compatibility with previous versions of NumPy, given the anticipated release of 2.0. The default `int` type of NumPy will change to `np.intp` in 2.0, and is not the same as Python's `int` which was equivalent to C `long`. See [this](https://numpy.org/devdocs/numpy_2_0_migration_guide.html#windows-default-integer) paragraph for more information.
Note: [This document](https://scikit.bio/devdoc/review.html) may also be helpful …
> NumPy 2.0 backwards compatibility and Windows UniFrac support

- skbio/metadata/_metadata.py
- skbio/stats/power.py
This PR contains three commits which fix about 450 warnings, and brings down the number of warnings to 75.
```
============================================================= 
3000 passed, 521 warnings in 39.72s 
=============================================================
```
```
============================================================= 
3000 passed, 75 warnings in 38.58s
============================================================= 
```
---
1)  The warning has been raised due to the deprecation of the convert_dtype parameter in the apply method. To address this issue, I have modified the code by splitting the line into two parts: the first part applies the method, and the second part converts the result to the appropriate type.
```
skbio/io/format/tests/test_sample_metadata.py: 10 …
```
> Resolved Warnings

- skbio/io/tests/test_registry.py
This PR will fix the final newline issues on Windows. On Windows, the line separator is `\r\n` while on linux and other systems it is `\n`. The changes here fix the last of these issues for the current codebase.
> Fix newline character issues for windows

- .github/workflows/ci.yml
- CHANGELOG.md
- Makefile
- aarch64.Dockerfile
- setup.py
Because we no longer ship .c files (#1958), the build process must always use Cython. Therefore, the environment variable `USE_CYTHON` may be deleted.
> Removed the option of not using Cython during build

- skbio/__init__.py
- skbio/io/format/sample_metadata.py
This PR does two things:
1) Adds `skbio.metadata.SampleMetadata` to `skbio/__init__.py`, such that the class can be imported by `from skbio import SampleMetadata`. Addresses #2055 .
2) Allows `SampleMetadata.read` to accept keyword arguments such as `default_missing_scheme`, which is useful when reading a structured metadata table. With this addition, one can do `SampleMetadata.read('metadata.tsv', default_missing_scheme='INSDC:missing')` or `skbio.io.read('metadata.tsv', into=SampleMetadata, default_missing_scheme='INSDC:missing')`
This patch makes `read` function like [`SampleMetadata.load`](https://scikit.bio/docs/latest/generated/skbio.metadata.SampleMetadata.load.html). In fact, the `load` method is not present in any other modules of skbio. It is likely an inheritance from q2. To …
> Elevated and added read parameters to sample metadata

- CHANGELOG.md
- README.rst
Currently, the Zenodo link in the README points to the 0.5.9 version. This PR updates the Zenodo link in the README to point to the DOI that always redirects to the most recent version.
> Fixed the Zenodo link in the README to always point to the most recent version

- skbio/tree/_tree.py
- skbio/tree/tests/test_tree.py
I examined the mechanism of loading and storing phylogenetic trees in scikit-bio, and realized that a major bottleneck is the following [three lines](https://github.com/scikit-bio/scikit-bio/blob/0131e023a72cc45d650032a1237c35f290c23805/skbio/tree/_tree.py#L93) during the initiation of a `TreeNode` instance:
```python
self._tip_cache = {}
self._non_tip_cache = {}
self._registered_caches = set()
```
These three private attributes significantly increased the memory and runtime burden.
Here, `_tip_cache` and `_non_tip_cache` are dictionaries to facilitate searching by node name. They are only needed at the root node of a tree (see `create_caches`). However, they are created for every single node, which causes a huge waste. `_registered_caches` is very useful in customizing node attributes in …
> TreeNode: Improved time and memory efficiency by making caches lazy

- CHANGELOG.md
- skbio/diversity/alpha/_base.py
- skbio/tree/_tree.py
- skbio/tree/tests/test_tree.py
Update: Some substantial work has been done to make the rooting functionality of `TreeNode` complete and robust. Specifically:
1. The current default behavior is preserved. Therefore no API break will happen in the downstream.
2. Meanwhile, a warning is displayed during executing the code and in the documentation, saying that the default behavior will change in 0.7.0. The approach to mimick the new default behavior using the current code is provided.
3. Added method `insert` and parameter `above`, such that the root can be placed inside a branch, making the resulting tree rooted.
4. Added parameter `branch_attrs`, such that one can customize which attributes are branch attributes and should be transferred to the other side of the branch when it is flipped during rerooting.
5. Added method …
> Improved tree rooting

- skbio/metadata/_intersection.pyx
This PR addresses issue #2072. The problem lied with how the previous code handled the floating point division.
> Fix cython segmentation error

- CHANGELOG.md
- skbio/tree/_tree.py
- skbio/tree/tests/test_tree.py
This PR did some minor but effective optimizations of the tree traversal methods: `preorder`, `postorder` and `levelorder`. Most notably, the performance of `levelorder` has been increased by some 4x fold. This is because the previous code used a Python `list` as a queue (FIFO), which is inefficient. This PR replaced it with a `deque`, which is highly efficient in left append and pop. Benchmarks on a tree with 200k tips showed (sec):
- Pre-order: 0.1273 -> 0.1118 (**12%** decrease)
- Post-order: 0.1543 -> 0.1524 (**1.2%** decrease)
- Level-order: 0.8084 -> 0.1935 (**76%** decrease)
This PR also enriched documentation of these methods.
---
- **It is your responsibility to disclose** code, documentation, or other content derived from external …
> Optimized tree traversal algorithms

- .github/workflows/ci.yml
- .github/workflows/release.yml
- doc/metatag.py
- doc/source/alignment.rst
- doc/source/diversity.rst
- doc/source/embedding.rst
- doc/source/index.rst
- doc/source/io.rst
- doc/source/metadata.rst
- doc/source/sequence.rst
- doc/source/stats.rst
- doc/source/table.rst
- doc/source/tree.rst
- doc/source/util.rst
- doc/source/workflow.rst
This PR adds meta description tags to the HTML files of individual documentation pages. These tags are automatically generated according to the first line of the docstring of each object. It provides a brief description of the webpage. This information is useful for search engines to understand the topic of the webpage.
***
Note: [This document](https://scikit.bio/devdoc/review.html) may also be helpful to see some of the things code reviewers will …
> Added meta description tags to documentation pages

- CHANGELOG.md
- doc/source/_templates/autosummary/class.rst
- doc/source/autoinherit.py
- doc/source/conf.py
- skbio/embedding/__init__.py
- skbio/io/__init__.py
- skbio/metadata/__init__.py
- skbio/sequence/__init__.py
- skbio/util/__init__.py
This PR simplified the documentation of scikit-bio. Previously, a substantial proportion of the entire documentation belonged to two categories of webpages. These pages are usually redundant or of little information. They make the navigation panel crowded and hard to navigate. They may also confuse crawlers of search engines.
1. Special methods (a.k.a., dunder methods or magic methods), such as `__eq__`, `__len__`. They were previously referred to as "built-in" in scikit-bio. Many of them are from Python, and they don't need to be documented. But some of them were explicitly implemented in scikit-bio.
2. Inherited methods, such as `DNA.frequencies`, which is inherited from `Sequence`. In the previous mechanism, all of them will have separate stub pages, causing redundancy.
This PR did two …
> Remodeled autosummary template for class

- skbio/io/__init__.py
- skbio/io/format/fasta.py
@qiyunzhu and @mortonjt this should address the documentation deficiency we discussed in the past regarding reading multi-FASTA files. Jamie, I believe you mentioned adding a line similar to this, `list(skbio.io.read(mock_fl, format="fasta", constructor=DNA))`, to any skbio object which returns a generator upon being read, which I will add to this PR if this first example looks good to each of you.
Note: [This …
> Update FASTA doc to include reading multi

- CHANGELOG.md
- skbio/io/_iosources.py
- skbio/io/tests/test_iosources.py
This PR addresses issue #2058, #1983, and #1421 with an extremely simple fix to add support for Python's `pathlib` module. Based on the examples from issues #2058 and #1983, I believe this enables `skbio.io.read` and `skbio.io.write` both to handle `Path` objects. Please test rigorously as this seems almost too easy!
Note: [This document](https://scikit.bio/devdoc/review.html) may also be helpful to see some of the things code reviewers will be …
> pathlib support for skbio.io

- CHANGELOG.md
- skbio/io/registry.py
This PR partially addresses issue #2059 by making the IO registry sniffer only try formats which make sense for a given skbio object passed to the `into` parameter of `skbio.read`.
For example, if a user is trying to read a file into a `TreeNode` object, it doesn't make sense for the sniffer to check if the file is FASTA format or any other format which cannot represent a tree.
* [] This pull request does not include code, documentation, or other …
> Make IO registry sniffer only sniff relevant formats for a given skbio object

- skbio/util/__init__.py
This is a very minor issue that I overlooked recently. @mataton Feel free to directly merge if it looks good to you. Thanks!
***
> Exposed `get_rng` in documentation

- CHANGELOG.md
- skbio/tree/_tree.py
- skbio/tree/tests/test_tree.py
This PR adds parameter `include_self` to `TreeNode.ancestors` to optionally include the initial node in the path (default: False). This logic is consistent with the newly added `path`, which has `include_ends`. With this parameter, one can easily generate a lineage from any taxon to the root.
@christapo I guess this addition can also make `path` simpler. What do you think?
This PR also improved the performance of `ancestors`. In my benchmarks:
Before: 40.3 ms ± 565 μs
After: 21.8 ms ± 194 μs
After (with `include_self=True`): 22.1 ms ± 278 μs
- **It is your responsibility to disclose** code, documentation, or other content derived from external source(s). If you have questions about whether something can be included in the project or how to give …
> Optimized `TreeNode.ancestors`

- CHANGELOG.md
- skbio/diversity/_driver.py
- skbio/diversity/tests/test_driver.py
Thank you @quliping for doing a comprehensive and critical assessment of skbio's beta diversity functionality #2125 . This PR addresses your comments by:
- Removing `mahalanobis` metric because it requires more samples than features, which is rarely the case in omic data analysis.
- Adding `jensenshannon` metric because it is a valid and commonly used beta diversity metric. Addressing #1541.
- Continuing to exclude `kulczynski1` metric based on the rationale in #1887.
- Letting `get_beta_diversity_metrics` display all metrics, not just UniFrac.
@ebolyen I want to bring this to your attention because it may impact q2-diversity's functionality.
***
- **It is your responsibility to disclose** code, documentation, or other content derived from external …
> Improving beta diversity metrics

- .github/workflows/ci.yml
- .github/workflows/release.yml
- .github/workflows/website.yml
- CHANGELOG.md
- setup.py
- skbio/stats/distance/_permdisp.py
- skbio/util/tests/test_misc.py
Upon further investigation into the segmentation fault found in issue #2137, it appears that while scikit-bio 0.6.2 is not compatible with Python 3.13, scikit-bio's current development version is compatible with Python 3.13. This will be verified by the CI tests either passing or failing.
Out of curiosity, I looked into the history of `_intersection.pyx`. Looks like I made a [commit](https://github.com/scikit-bio/scikit-bio/commit/5e04026c488a101a61419d614325a1ff23e2bbcb#diff-28213528b0b5444704b20f32b2020c39e6b251a3bbe4989df039c917233fc127R97) on July 8th that fixed the segmentation fault on Windows. This was one day after scikit-bio 0.6.2 released on July 7th. 
- **It is your responsibility to disclose** code, documentation, or other content …
> Python 3.13 Support

- CHANGELOG.md
- skbio/stats/ordination/_principal_coordinate_analysis.py
- skbio/stats/ordination/tests/test_principal_coordinate_analysis.py
This pull request allows the number of dimensions parameter in the PCoA function to accept float values between 0 and 1, in addition to integers. This will allow the user to input fractional numbers to compute percentage variance. 
> Allowed PCoA's number of dimensions to accept float values to capture fractional cumulative variance

- CHANGELOG.md
- doc/source/_templates/TreeNode.rst
- skbio/tree/__init__.py
- skbio/tree/_tree.py
- skbio/tree/tests/test_bme.py
- skbio/tree/tests/test_gme.py
- skbio/tree/tests/test_tree.py
- skbio/util/_warning.py
Following our internal discussions on tree comparison metrics, I have implemented or updated multiple common metrics, following their accurate definitions in the literature. The results were compared with those of popular programs to ensure consistency. A strong focus was placed on the flexibility of the metrics, such that a larger spectrum of measurements other than published ones may be calculated. Meanwhile, the original default behaviors of the relevant functions are largely preserved. Additionally, documentation has been significantly enriched to inform the users how to use use metrics and what to expect.
A summary of code added or changed in this large PR:
- The **Robinson-Foulds (RF) distance** (`compare_rfd`) was updated to match its original definition, which is based on …
> Improved topological analysis and comparison

- CHANGELOG.md
- setup.py
- skbio/tree/_cutils.pyx
- skbio/tree/_nj.py
- skbio/tree/tests/test_nj.py
This PR optimizes [**neighbor joining (NJ)**](https://en.wikipedia.org/wiki/Neighbor_joining), a classical algorithm for phylogenetic tree building based on a distance matrix among taxa. The new algorithm is 20-30x faster than the old one, and is competitive when compared with popular implementations in the community.
FYI @christapo @RaeedA 
The old implementation was already quite efficient, due to the use of NumPy vectorization throughout the algorithm. The new algorithm further achieves performance gain because of:
1. The agglomerative clustering process does not create intermediate matrices and arrays during each iteration. Instead, it re-uses the same block of memory space over and over. This not only improves memory efficiency but also reduces the time overheads of allocating new …
> Optimized the neighbor joining (NJ) tree building algorithm

- CHANGELOG.md
- skbio/tree/_tree.py
- skbio/tree/tests/test_tree.py
The bug is that when a `TreeNode` object is provided to the `TreeNode.find` method, it will be returned directly, even if the node is not present in the current tree (e.g., in another tree). This PR fixed it.
***
> Fixed a `TreeNode.find` bug

- skbio/tree/_nj.py
- skbio/tree/tests/test_nj.py
Added `inplace` mode, which further reduces memory consumption by avoiding creating a copy of the distance matrix but instead manipulating the distance matrix in place. This destroys the input data though. A similar mechanism was already used in `pcoa`.
Test on 9,232 taxa:
Baseline: 819,204 KB
`inplace=False` (default): 1,488,096 KB (+668,892)
`inplace=True`: 822,284 KB (+3,080)
***
Note: [This document](https://scikit.bio/devdoc/review.html) may …
> Optimized neighbor-joining (NJ) memory usage

- CHANGELOG.md
- doc/source/_templates/TreeNode.rst
- skbio/tree/_tree.py
- skbio/tree/tests/test_bme.py
- skbio/tree/tests/test_gme.py
- skbio/tree/tests/test_nj.py
- skbio/tree/tests/test_nni.py
- skbio/tree/tests/test_tree.py
- skbio/tree/tests/test_upgma.py
The tip-to-tip distance in a phylogenetic tree may be called the [cophenetic distance](https://en.wikipedia.org/wiki/Cophenetic). The correlation between cophenetic distance matrices may be called the [cophenetic correlation](https://en.wikipedia.org/wiki/Cophenetic_correlation). These notions are commonly used in hierarchical clustering. Therefore, this PR renames `tip_tip_distances` and `compare_tip_distances` as `cophenet` and `compare_cophenet`, respectively. The old names are preserved as aliases, and will last for a while. The output of `cophenetic` is consistent with SciPy's [`cophenet`](https://docs.scipy.org/doc/scipy/reference/generated/scipy.cluster.hierarchy.cophenet.html) (for ultrametric trees), ape's [`cophenetic`](https://rdrr.io/cran/ape/man/cophenetic.phylo.html), and …
> Renamed tip-tip distance as cophenetic distance

- .pre-commit-config.yaml
Updating default ruff version for the pre-commit hooks. The rationale for pre-commit not allowing unpinned latest versions is [here](https://pre-commit.com/#using-the-latest-version-for-a-repository).
> Update ruff version

- CHANGELOG.md
- doc/source/_templates/TreeNode.rst
- skbio/tree/_tree.py
- skbio/tree/tests/test_tree.py
This PR improves the performance and customizability of `TreeNode.total_length` (renamed from `descending_branch_length`; old name kept as an alias). Test on a tree with 16k tips:
Entire tree:
- Before: 23.8 ms ± 474 μs
- After: 10.9 ms ± 404 μs
5000 tips
- Before: 56.8 ms ± 2.09 ms
- After: 10.7 ms ± 724 μs
2000 tips
- Before: 38.7 ms ± 809 μs
- After: 4.79 ms ± 118 μs
1000 tips
- Before: 32.5 ms ± 1.09 ms
- After: 2.81 ms ± 47.9 μs
***
Note: [This …
> Optimized the calculation of total branch lengths of a clade

- CHANGELOG.md
- skbio/stats/composition.py
Per our discussion, this PR temporarily hides the function from the documentation. The API still exists and can be called. But the user won't know that it is there.
> Temporarily hid `dirmult_lme` from documentation

- CHANGELOG.md
- doc/source/conf.py
Addresses #2181 by modifying the `linkcode_resolve` function to check if an object has a `__wrapped__` attribute. If it does, then the object becomes the wrapped function itself, instead of remaining the decorator.
> Fix `[source]` linking issue in documentation

- skbio/diversity/_util.py
- skbio/diversity/alpha/_pd.py
- skbio/diversity/beta/_unifrac.py
- skbio/diversity/tests/test_util.py
Addresses #2182. Additionally removes the `_check_taxa_alias` function, which is no longer required because of the `params_aliased` decorator, although @qiyunzhu your input in this regard would be appreciated.
> Alias `otu_ids` using new decorator

- CHANGELOG.md
- skbio/util/_plotting.py
- skbio/util/tests/test_plotting.py
An issue with scikit-bio's current plotting functionality is that generating plots automatically by default can lead to kernel crashes for large objects such as `DistanceMatrix`. This is discussed further in issue #2215. To overcome this, this PR removes two functions from the `PlottableMixin` class:  `_repr_png_` and `_repr_svg_`. Removing these functions results in the default representation of an object which inherits from `PlottableMixin` to be that object's respective `_str_` representation. If the user wishes to plot the object, they may use the object's `plot()` method. The only objects in scikit-bio which inherit from `PlottableMixin` are `DistanceMatrix`, `DissimilarityMatrix`, and `OrdinationResults`.
- **It is your responsibility to …
> Remove autoplotting functionality to enable inplace operations on large objects

- skbio/tree/_c_nj.pyx
- skbio/tree/_nj.py
- skbio/tree/tests/test_nj.py
Some trivial tweaks of the neighbor-joining (NJ) algorithm. No visible performance gain. But one important thing to note:
It is favorable to support both float32 and float64 in scikit-bio algorithms. Here is a [proposal](https://github.com/scikit-learn/scikit-learn/wiki/GSoC-2016-Proposal:-Adding-fused-types-to-Cython-files) by scikit-learn. scikit-bio's `DistanceMatrix` already supports both float32 and float64 ([code](https://github.com/scikit-bio/scikit-bio/blob/bb0332773c9267bc77ba2601c9b4843144393289/skbio/stats/distance/_base.py#L138)), and some of scikit-bio's core algorithms such as PCoA ([code](https://github.com/scikit-bio/scikit-bio/blob/main/skbio/stats/ordination/_cutils.pyx)) and PERMANOVA ([code](https://github.com/scikit-bio/scikit-bio/blob/main/skbio/stats/distance/_cutils …
> Tweaking NJ algorithm

- pyproject.toml
- setup.py
This PR adds dependency and package metadata to the `pyproject.toml` file, in line with modern best practices. Currently scikit-bio's package metadata is described in the `setup.py` file, which many modern development tools such as [deps.dev](https://deps.dev/) do not support.
> Move package metadata to pyproject.toml

- .github/workflows/build_wheels.yml
- .github/workflows/release.yml
- .github/workflows/wheels.yml
- pyproject.toml
Add wheel building with `cibuildwheel`
Addresses lack of pre-built wheels on PyPI, which makes scikit-bio difficult to install (especially on Windows). Implements automated wheel building using `cibuildwheel`.
- Add .github/workflows/wheels.yml to build wheels for all platforms (Linux, macOS, Windows) and Python 3.9-3.13
- Update .github/workflows/release.yml to use the new wheels workflow
- Add cibuildwheel configuration to pyproject.toml
- Users can now pip install scikit-bio without needing compilers
- Installation time reduced
- Significantly improves Windows user experience
Resolves #588 .
- **It is your responsibility to disclose** code, documentation, or other content derived from external source(s). If you have questions about whether …
> WIP: Provide pre-built binaries for scikit-bio using cibuildwheel

- CHANGELOG.md
- skbio/alignment/_path.py
- skbio/alignment/tests/test_path.py
Bug was that when a CIGAR string starts with an insertion (`I`), it will be ignored. For example, `1I3M` will become `3M`.
***
> Fixed a bug in `AlignPath.from_cigar`

- .github/workflows/ci.yml
- .github/workflows/release.yml
- .github/workflows/website.yml
In the previous status, when the GitHub Actions workflows were executed, a warning was raised:
> 'Mambaforge' variants are now equivalent to 'Miniforge3'. In the future, we will ignore with a warning and use 'Miniforge3'. Eventually, using 'Mambaforge' will throw an error. Please change to 'Miniforge3' at your earliest convenience.
Therefore, this PR aims to resolve this warning.
According to [setup-miniconda/action.yml](https://github.com/conda-incubator/setup-miniconda/blob/main/action.yml), if both `miniconda-version` and `miniforge-variant` are not specified, they will default to the latest Miniforge3. This is what we desire.
***
The 2nd commit also addresses a (maybe temporary) Sphinx problem: It reads the git timestamp for some reason (although I don't know what reason), whereas …
> Removed miniforge version and patched checkout in CI workflow

- .github/workflows/wheels.yml
- pyproject.toml
Previously the test command for ensuring built wheels worked correctly was simply:
```
"python -c \"import skbio; print(skbio.__version__)\""
```
Due to the long runtime of scikit-bio's tests, this command was used to check minimal functionality of wheels. This PR changes the workflow so that during PR's the simple import test is run, but on releases the full test suite of scikit-bio (minus tests requiring matplotlib) is run for each wheel created. This ensures build quality of all wheels uploaded to PyPI, while still allowing quick CI runs for PRs.
- **It is your responsibility to disclose** code, documentation, or other content derived from external source(s). If you have questions about whether something can be included in the project or how to …
> Run unit-tests on wheels before release

- .codecov.yml
- .coveragerc
- skbio/util/_testing.py
This PR puts the `util/_typing` module into the ignore category for unit test coverage. It also deletes an unused testing function.
> Skip unit tests for typing module

- CHANGELOG.md
- skbio/stats/distance/_permdisp.py
- skbio/stats/ordination/_principal_coordinate_analysis.py
- skbio/stats/ordination/tests/test_principal_coordinate_analysis.py
This PR changes the parameter name `number_of_dimensions` to `dimensions` in `pcoa` and `permdisp`. `number_of_dimensions` will remain a valid alias of the parameter, thanks to the `@params_aliased` decorator.
> Change `number_of_dimensions` to `dimensions`

- CHANGELOG.md
- skbio/stats/distance/_anosim.py
- skbio/stats/distance/_bioenv.py
- skbio/stats/distance/_permanova.py
- skbio/stats/distance/_permdisp.py
- skbio/stats/ordination/_principal_coordinate_analysis.py
This PR changes the parameter name `distance_matrix` to `distmat` in `pcoa`, `bioenv`, `anosim`, `permanova`, and `permdisp`. `distance_matrix` will remain a valid alias of the parameter, thanks to the @params_aliased decorator.
> Rename `distance_matrix` parameter to `distmat`

- skbio/table/_tabular.py
The `AnnData.X` attribute of an anndata object may be things other than numpy arrays. This PR converts the attribute to a numpy array upon being "ingested" into the scikit-bio system.
> Cast AnnData X attribute to numpy array
