- CHANGELOG.md
- licenses/qiita.txt
- skbio/stats/distance/_base.py
- skbio/stats/distance/tests/test_base.py
- skbio/util/__init__.py
- skbio/util/_misc.py
- skbio/util/tests/test_misc.py
> ENH: report duplicate IDs during DissimilarityMatrix validation

- CHANGELOG.md
- setup.py
- skbio/__init__.py
> REL: update to 0.2.3-dev

- .travis.yml
This should tell Travis to post updates to scikit-bio's gitter chat room when:
- a build fails
- a branch that was previously failing is fixed
> CI: travis-ci & gitter integration

- CONTRIBUTING.md
> DOC: update developer docs to mention the on deck label

- skbio/tree/_trie.py
> STY: Fixed flake8/pep8 error

- skbio/alignment/_alignment.py
- skbio/tree/_trie.py
Fixes #840, but I had a few issues:  :hand: 
I got this error when running the nosetests so the tests did **not** pass...  you can deny me.  It's okay, I understand...  just trying to learn here!  Thanks! 
"ImportError: No module named _ssw_wrapper"
Also, I noticed that there was a pep8 error in _trie.py so I fixed that too but didn't make an issue for it since it was just pep8.
> Fixes #840 DOC: improve documentation for teaching purposes

- doc/README.md
- doc/source/development/coding_guidelines.rst
- skbio/__init__.py
- skbio/diversity/alpha/_ace.py
- skbio/diversity/alpha/_chao1.py
- skbio/diversity/alpha/_gini.py
- skbio/diversity/alpha/_lladser.py
- skbio/diversity/alpha/tests/__init__.py
- skbio/diversity/alpha/tests/test_ace.py
- skbio/diversity/alpha/tests/test_base.py
- skbio/diversity/alpha/tests/test_chao1.py
- skbio/diversity/alpha/tests/test_gini.py
- skbio/draw/tests/__init__.py
- skbio/io/tests/test_clustal.py
- skbio/sequence/tests/__init__.py
- skbio/sequence/tests/test_genetic_code.py
- skbio/stats/distance/tests/__init__.py
- skbio/stats/spatial.py
- skbio/stats/tests/__init__.py
- skbio/stats/tests/test_gradient.py
- skbio/stats/tests/test_spatial.py
- skbio/tests/__init__.py
- skbio/tests/test_workflow.py
- skbio/tree/_trie.py
- skbio/util/tests/__init__.py
- skbio/util/tests/test_testing.py
- skbio/workflow.py
These aren't necessary and were already partially removed.
> MAINT: remove shebang lines from codebase

- README.rst
Somehow this slipped through the cracks in #808
> Fix test instructions in README

- CHANGELOG.md
- README.rst
- RELEASE.md
- doc/README.md
- doc/source/development/coding_guidelines.rst
- skbio/test.py
- skbio/util/_testing.py
> Interactive tests

- CHANGELOG.md
- skbio/io/_base.py
- skbio/io/fastq.py
- skbio/io/tests/test_base.py
Addresses some of the concerns in #907 by making the quality conversion less costly.
> ENH: quality score conversions in fastq are faster

- CHANGELOG.md
- skbio/io/fasta.py
- skbio/sequence/_nucleotide_sequence.py
- skbio/sequence/_sequence.py
- skbio/sequence/tests/test_sequence.py
- skbio/util/_misc.py
A few more changes that have nothing to do with each other and this could be a congressional bill!
> optimized complement and removed hooks

- skbio/sequence/_sequence.py
- skbio/sequence/tests/test_sequence.py
Addresses part of #949.
@anderspitman or @ebolyen can you please review?
> ENH: add Sequence.metadata property setter

- skbio/sequence/_nucleotide_mixin.py
- skbio/sequence/tests/test_nucleotide_sequences.py
> Gc frequency content

- skbio/sequence/_sequence.py
- skbio/sequence/tests/test_sequence.py
Early draft, not ready for review.
> Optimize sequence init

- skbio/sequence/_sequence.py
- skbio/sequence/tests/test_sequence.py
100% speedup for optimized path (ie no positional metadata) when combined with #976.
@jairideout @ebolyen ready for review
> Iter kmers performance

- setup.py
This would have sucked to forget.
> TST: add format test data to package data

- skbio/io/format/fasta.py
- skbio/io/format/fastq.py
- skbio/io/format/qseq.py
- skbio/sequence/__init__.py
- skbio/sequence/_dna.py
- skbio/sequence/_protein.py
- skbio/sequence/_rna.py
- skbio/sequence/_sequence.py
Underlying sequences are immutable, but metadata and positional
metadata are mutable
> Update docs about Sequence mutability

- CHANGELOG.md
- skbio/sequence/_iupac_sequence.py
- skbio/sequence/tests/test_iupac_sequence.py
Fixed Issue #1005 - added to_regex method to IUPACSequence, with unit-tests.
> Issue 1005

- index.html
fixes #1016 
I switched both links to be to the Enthought videos since the old slideshow isn't working at the moment and I don't have a good way to actually export our newest one.
> WEB: add title and scipy2015 presentation

- CHANGELOG.md
- skbio/tree/_tree.py
- skbio/tree/tests/test_tree.py
- skbio/util/__init__.py
- skbio/util/_warning.py
Contains the commits in #882 and updates based on code review there. Fixes #791.
@ebolyen can you please review?
> ENH: TreeNode.tip_tip_distances supports nodes without associated length

- skbio/stats/power.py
> DOC/TST: speed up skbio.stats.power doctests

- skbio/tree/_tree.py
- skbio/util/_misc.py
- skbio/workflow.py
@ebolyen and I worked on this together. Fixes #771.
> MAINT: remove exclamatory error messages

- CHANGELOG.md
- skbio/diversity/alpha/_ace.py
- skbio/diversity/alpha/_base.py
- skbio/diversity/alpha/_chao1.py
- skbio/diversity/alpha/_gini.py
This PR contains the commits in #574 and updates based on code review there. Addresses part of #321.
@ebolyen can you please review?
> DOC: additional alpha diversity equations

- CHANGELOG.md
- skbio/io/format/_base.py
- skbio/io/format/fasta.py
- skbio/io/format/fastq.py
- skbio/io/format/qseq.py
- skbio/io/format/tests/test_fasta.py
- skbio/io/format/tests/test_fastq.py
- skbio/sequence/_dna.py
- skbio/sequence/_iupac_sequence.py
- skbio/sequence/_protein.py
- skbio/sequence/_rna.py
- skbio/sequence/_sequence.py
- skbio/sequence/tests/test_iupac_sequence.py
- skbio/sequence/tests/test_sequence.py
Behaves just like `DNA`, `RNA`, and `Protein`
> ENH: add `lowercase` keyword to `Sequence`.

- .travis.yml
> CI: test cython against py3.3, drop extra py2.7 build

- CHANGELOG.md
- skbio/sequence/_dna.py
- skbio/sequence/_rna.py
- skbio/sequence/tests/test_rna.py
> add reverse_transcribe to RNA class

- .travis.yml
- Makefile
- setup.py
**DO NOT MERGE:** This should hopefully trigger a failure with travis-ci. See #1061
> CI: don't install scikit-bio with -e

- MANIFEST.in
- Makefile
- asv.conf.json
- benchmarks/benchmarks.py
> Add asv config and benchmarks

- doc/source/_templates/autosummary/class.rst
- doc/source/conf.py
Some hacky things are happening, but it beats redistributing numpydoc!
> DOC: Only dunders we have created will appear in the documentation

- CHANGELOG.md
- skbio/diversity/alpha/__init__.py
- skbio/diversity/alpha/_base.py
- skbio/diversity/alpha/tests/test_base.py
Fixes #1068 
I'm new at this and I'm sure there are style issues.
Suggestions are welcome!
> Add pielous evenness

- CHANGELOG.md
- skbio/diversity/alpha/__init__.py
- skbio/diversity/alpha/_base.py
- skbio/diversity/alpha/tests/test_base.py
> DEP: remove skbio.diversity.alpha.equitability in favor of pielou_e

- skbio/sequence/_iupac_sequence.py
> Improve error for sequence with lowercase characters

- skbio/sequence/_sequence.py
> BUG: Changed ``__nonzero__`` to ``__bool__`` and aliased.

- doc/source/conf.py
Converts the ClassName to camel_case to indicate an instance, and will abbreviate if greater than 10 characters.
> DOC: Certain dunders have a friendlier display name in the link

- CHANGELOG.md
- skbio/sequence/_sequence.py
- skbio/sequence/tests/test_sequence.py
> BUG: fix empty metadata propogating incorrectly

- CHANGELOG.md
- skbio/alignment/_tabular_msa.py
- skbio/sequence/_sequence.py
- skbio/sequence/tests/test_sequence.py
Also adds `TabularMSA._get_position(i)`.
> ENH: add Sequence.concat classmethod

- skbio/stats/ordination/_utils.py
- skbio/stats/ordination/tests/test_util.py
Test result was wrong.
Fixes #1144
> BUG: scale needs to convert input to float64 to work in-place

- ci/pip_requirements.txt
- doc/source/conf.py
> DOC: Keep numpydoc alive for a few more days

- CHANGELOG.md
- skbio/stats/distance/_base.py
- skbio/stats/distance/tests/test_base.py
Adds ``to_dataframe`` method and test.
> Fixes #757

- CHANGELOG.md
- skbio/io/format/phylip.py
Also added changelog mention. Fixes #1006. Fixes #1019.
> DOC: update PHYLIP format docs to describe new sniffer and reader

- skbio/alignment/_tabular_msa.py
- skbio/alignment/tests/test_tabular_msa.py
> ENH: TabularMSA.__contains__

- .travis.yml
- ci/conda_requirements.txt
- ci/pip_requirements.txt
- doc/README.md
- doc/source/conf.py
- setup.py
- skbio/alignment/tests/test_tabular_msa.py
Fixes #1177. Fixes #661.
@ebolyen and I pair-programmed this together.
> CI: test against Python 3.5

- skbio/alignment/_tabular_msa.py
- skbio/alignment/tests/test_tabular_msa.py
- skbio/sequence/_sequence.py
> ENH: TabularMSA.join

- skbio/diversity/__init__.py
- skbio/diversity/_driver.py
- skbio/diversity/alpha/__init__.py
- skbio/diversity/alpha/_faith_pd.py
- skbio/diversity/beta/__init__.py
- skbio/diversity/beta/_unifrac.py
One issue that needs to be sorted out is that the plots are now showing up much bigger than in the 0.4.0 docs and as a result are being cut off in some cases. For example:
Has anyone else run into this?
> reorganization of skbio.diversity documentation

- CHANGELOG.md
- setup.py
> BUG: add missing nose dependency to setup.py's `install_requires`

- skbio/sequence/__init__.py
- skbio/sequence/_sequence.py
> DOC: update Sequence docs to indicate generic/nonbiological nature

- skbio/diversity/_util.py
This was useful while I was trying to debug an issue with running UniFrac on real data.
> DOC: improved error message

- skbio/alignment/_indexing.py
- skbio/alignment/_repr.py
- skbio/alignment/_tabular_msa.py
- skbio/alignment/tests/test_tabular_msa.py
- skbio/sequence/_sequence.py
- skbio/sequence/tests/test_sequence.py
Still need to add docs
@jairideout would you mind giving this a first pass?
fixes #1102 
fixes #1086 
fixes #1088
> TabularMSA: __getitem__, loc, iloc

- doc/source/_static/style.css
- doc/source/conf.py
fixes #1179 
Also will now use the abbreviations of `tree` and `msa` in the dunder api docs.
> WEB: fixed colors

- CHANGELOG.md
- skbio/stats/composition.py
- skbio/stats/tests/test_composition.py
Quick fix addressing #1241 
Thanks for pointing out this issue @johnchase .  Let me know if there is anything more that should be improved on the documentation.
> BUG: Addressing #1241

- skbio/stats/tests/test_composition.py
Swapping out the mann-whitney U-test with a t-test.
Note, this only swaps out this statistical test in the broken test cases.
> Addresses #1259

- skbio/io/format/clustal.py
- skbio/io/format/fastq.py
> DOC/MAINT: Fixed missing language highlighting for fastq, clustal

- skbio/io/tests/test_util.py
> TST: compare last 8 bytes of gzip files

- skbio/__init__.py
- skbio/io/format/stockholm.py
- skbio/sequence/distance.py
- skbio/tree/_tree.py
In preparation for the release
> MAINT: updated version strings to new release 0.4.2

- CHANGELOG.md
- skbio/sequence/_sequence.py
- skbio/sequence/distance.py
- skbio/sequence/tests/test_distance.py
- skbio/sequence/tests/test_sequence.py
> Adds `kmer_distance` function to skbio.sequence.distance

- CHANGELOG.md
- skbio/sequence/_sequence.py
- skbio/sequence/tests/test_sequence.py
> Adds `replace` method to `skbio.sequence`

- README.rst
Added conda badges from https://anaconda.org/biocore/scikit-bio/badges in `README.rst`
Fixes: https://github.com/biocore/scikit-bio/issues/1302
> Conda Badges

- ci/conda_requirements.txt
The rationale for this temporary hack is described in #1308.
> HACK: temporary pandas version cap in CI

- README.rst
Resolves the last point from #1012 (which can be closed post-merge).
> Add debian install instructions to readme

- skbio/stats/composition.py
Resolving confusion in ancom documentation
> DOC: Resolving ANCOM documentation confusion

- skbio/diversity/beta/_unifrac.py
Found them while reading the docs :eyes:
> DOC: Fixing typos

- README.rst
> DOC: add Depsy badge

- CHANGELOG.md
- skbio/tree/_tree.py
- skbio/tree/tests/test_tree.py
> Issues #1247 and #807

- CHANGELOG.md
- README.rst
- setup.py
> REV: remove numpy bootstrap hack in setup.py

- CHANGELOG.md
- skbio/io/_iosources.py
- skbio/io/tests/test_util.py
- skbio/io/util.py
> skbio.io now supports NamedTemporaryFiles

- CHANGELOG.md
- skbio/tree/_majority_rule.py
- skbio/tree/_tree.py
- skbio/tree/tests/test_majority_rule.py
- skbio/tree/tests/test_tree.py
Contains the commits in #1193, thanks @terrycojones! I added some unit tests, fixed a few lingering hardcoded `TreeNode` references, and updated the changelog.
> ENH: TreeNode subclass support

- CHANGELOG.md
- skbio/io/registry.py
- skbio/io/tests/test_registry.py
> Adds more descriptive error message to registry

- CHANGELOG.md
- skbio/alignment/_pairwise.py
- skbio/alignment/_tabular_msa.py
- skbio/alignment/tests/test_tabular_msa.py
Caught this while going through the cookbook.
> ENH/BUG: Fix performance of aligners

- doc/source/conf.py
- skbio/stats/ordination/_ordination_results.py
Pair programmed with @jairideout and @jakereps
> MAINT: Update OrdinationResults.plot for new matplotlib

- CHANGELOG.md
I wasn't sure if you wanted such a measly PR, but it seemed only right to contribute it since I had noticed the typo. Thanks to everyone for the work on `scikit-bio`. Cheers.
> Correct CHANGELOG.md typo TabularMSA

- skbio/util/_decorator.py
> REF: simplified classonlymethod implementation

- CHANGELOG.md
- skbio/tree/_tree.py
A smarter shearing algorithm. Observed ~25% reduction in runtimes when benchmarking on Greengenes 85% and 88% tree randomly pulling 10% of the tips.
> PERF: 25% reduction in runtime for TreeNode.shear

- CHANGELOG.md
- skbio/stats/composition.py
- skbio/stats/tests/test_composition.py
- skbio/util/_decorator.py
Fixing _check_orthogonality
Addressing #1393
> ENH: Addressing #1393

- checklist.py
First use-case for this came up in #1414.
> CI/ENH: add directive to checklist.py to ignore copyright header validation in individual files

- skbio/metadata/_interval.py
- skbio/metadata/tests/test_interval.py
1. add `IntervalMetadata.num_interval_features`
2. add `upper_bound`
3. add copy methods
@jairideout , ready for review.
> modification to IntervalMetadata

- skbio/metadata/_interval.py
- skbio/metadata/tests/test_interval.py
This is related to #1423 , specifically https://github.com/biocore/scikit-bio/pull/1423#discussion_r80286443
* coordinates system:
`.locations` -> `.bounds`
`.boundaries` -> `.fuzzy`
reverse True/False for fuzzy
add a example to explain in docstring clearly
* update eq/ne:
test lower/upper_bound for equality
use "==" for ne implementation
* update and add tests
* delete a repreated test test_query_negative
* update repr
>  clarify the boundary config of interval features

- skbio/io/format/_blast.py
Pinging @jairideout for later (he is on vacation atm): do you think the registry should be doing something like this anyways? It knows the appropriate lifetimes for these objects and it could neuter `close` until it was actually time to close.
Partially fixes #1435 
@RNAer, @wasade, or anyone else interested, would you be able to review/merge? Thanks!
> HACK: fixes pd.read_csv close issue

- CHANGELOG.md
- skbio/metadata/_interval.py
- skbio/metadata/_repr.py
- skbio/metadata/tests/test_interval.py
- skbio/sequence/_dna.py
- skbio/sequence/_grammared_sequence.py
- skbio/sequence/_nucleotide_mixin.py
- skbio/sequence/_protein.py
- skbio/sequence/_rna.py
- skbio/sequence/_sequence.py
- skbio/sequence/tests/test_dna.py
- skbio/sequence/tests/test_grammared_sequence.py
- skbio/sequence/tests/test_nucleotide_sequences.py
- skbio/sequence/tests/test_rna.py
- skbio/sequence/tests/test_sequence.py
This is ready for review, @mortonjt and @wasade . Thanks!
> Hook ``IntervalMetadataMixin`` to `Sequence` and `GrammaredSequence` classes.

- CHANGELOG.md
- skbio/stats/distance/_base.py
- skbio/stats/distance/tests/test_base.py
This commit is based on the work by @virginiasaulnier in
https://github.com/biocore/scikit-bio/pull/1406 with final review changes made.
Fixes #1397.
> ENH: add `DistanceMatrix.to_series` method

- CHANGELOG.md
- skbio/__init__.py
> MAINT: Bump to 0.5.1-dev

- skbio/stats/composition.py
Replacing the old reference with a much more up to date reference.
The book can be found [here](http://onlinelibrary.wiley.com/book/10.1002/9781119003144) and has quite a few more updated samples.
> Updating references for compositional functions

- index.html
**Note:** [REVIEWING.md](REVIEWING.md) may also be helpful to see some of the things code reviewers will be verifying when reviewing your pull request.
This project heavily relies on the data structures in scikit-bio.  I think it'll make a nice addition to this list :)
> Adding link to gneiss

- PULL_REQUEST_TEMPLATE.md
Relative links don't appear to work so switched to full URLs.
**Note:** [REVIEWING.md](REVIEWING.md) may also be helpful to see some of the things code reviewers will be verifying when reviewing your pull request.
> DOC/BUG: fix links in PR template

- skbio/stats/distance/_base.py
- skbio/stats/ordination/_ordination_results.py
Importing matplotlib in IPython triggers a connection to the window manager
which may not be available (when running in a server). Thus, this would cause
IPython to exit, making skbio unusable in that situation.
No public facing changes
> BUG Do not import matplotlib at module level

- CHANGELOG.md
- setup.cfg
- setup.py
- skbio/stats/ordination/tests/test_ordination_results.py
- skbio/util/_testing.py
> Specify test_suite.  Fixes biocore/scikit-bio#1341

- .travis.yml
- skbio/alignment/tests/test_pairwise.py
- skbio/alignment/tests/test_ssw.py
- skbio/diversity/alpha/tests/test_faith_pd.py
- skbio/io/format/tests/test_blast6.py
- skbio/io/format/tests/test_qseq.py
- skbio/io/tests/test_registry.py
- skbio/sequence/_protein.py
- skbio/sequence/tests/test_rna.py
- skbio/stats/power.py
- skbio/tree/tests/test_nj.py
- skbio/util/tests/test_decorator.py
- skbio/util/tests/test_testing.py
- skbio/workflow.py
Fixed a bug in skbio/stats/power.py and added newlines to
pass pyflake tests
> BUG: passing tests in python 3.6 - references #1497

- CHANGELOG.md
- skbio/tree/_tree.py
- skbio/tree/tests/test_tree.py
> FIX: fixing `include_self` parameter in `skbio.TreeNode.tips``

- CHANGELOG.md
- ci/pip_requirements.txt
- doc/source/conf.py
- setup.py
- skbio/alignment/_indexing.py
- skbio/alignment/_tabular_msa.py
- skbio/alignment/tests/test_tabular_msa.py
- skbio/diversity/_block.py
- skbio/metadata/_mixin.py
- skbio/stats/gradient.py
- skbio/stats/ordination/_ordination_results.py
- skbio/stats/tests/test_composition.py
- skbio/stats/tests/test_gradient.py
Made the following compatibility updates to fix the longstanding Travis-CI failures and make the codebase a little more futureproof:
- The codebase is now compatible with pandas >=0.19.2, including the latest pandas release (0.20.3), which introduced a number of backwards-incompatible changes.
- Fixed doc build failures by unpinning numpydoc version (latest PyPI numpydoc release is now compatible with latest Sphinx release).
- Fixed all deprecation warnings coming from third-party packages -- most were pandas deprecations, and one was from `scipy.stats`.
- Fixed docs in a couple of places that weren't compatible with numpydoc.
Fixes #1497
Fixes #1511
Fixes #1531
---
**Note:** [REVIEWING.md](https://github.com/biocore/scikit-bio/blob/master/REVIEWING …
> MAINT: compat with new pandas and numpydoc; fix deprecation warnings

- CHANGELOG.md
- ci/conda_requirements.txt
- setup.py
- skbio/diversity/_driver.py
- skbio/diversity/tests/test_driver.py
> Fixes 1549

- CHANGELOG.md
- skbio/stats/ordination/_correspondence_analysis.py
- skbio/stats/ordination/tests/test_correspondence_analysis.py
This PR addresses issue #1345 and essentially just updates PR #1515 from @nreeve17 to the latest master. 
We might also change the variable name if desired. 
--------------------------
> Adding proportion of variance explained to ca (updates #1515)

- .travis.yml
- CHANGELOG.md
- README.rst
- skbio/__init__.py
* removed broken badge in readme.rst
* update travis to test both linux and Mac
> update version to 0.5.2-dev

- CHANGELOG.md
- skbio/tree/_tree.py
- skbio/tree/tests/test_tree.py
#Please complete the following checklist:
***
Dear all, I am starting to push codes that are relevant to phylogenetic tree operations, following our previous discussions during the code reviews and the scikit-bio code sprint. The codes were already prototyped in [Horizomer](https://github.com/biocore/horizomer/blob/master/horizomer/utils/tree.py), rigorously tested and reviewed by multiple people.
For the current pull request, I am adding a very simple method to `TreeNode` to get the support value of a given node. This operation is very essential in many applications where people care how …
> added TreeNode method `support`

- skbio/stats/ordination/_canonical_correspondence_analysis.py
> DOC: Fix small typo in the docs

- .eggs/README.txt
- CHANGELOG.md
- ci/conda_requirements.txt
> Pandas==0.22.0

- skbio/stats/ordination/_principal_coordinate_analysis.py
> Add missing stability decorator for pcoa_biplot

- CHANGELOG.md
- skbio/__init__.py
- skbio/alignment/_pairwise.py
- skbio/diversity/_driver.py
- skbio/sequence/_grammared_sequence.py
- skbio/tree/_tree.py
These changes are made in accordance to the instructions in the "Prep the release" section of [this document](https://github.com/biocore/scikit-bio/blob/master/RELEASE.md).
----------------------
> REL: Make changes for release 0.5.3

- setup.py
As it turns out #1584 was incomplete. The build for pip failed, but worked when I made this change.
------------------------------------
> BLD: Fix pandas version in setup.py

- CHANGELOG.md
- skbio/__init__.py
> REL: Bump version strings and update changelog

- CHANGELOG.md
- skbio/__init__.py
Notes / Questions -- please confirm @ElDeveloper :
1. There was one @deprecated that is due for removal, what I presume is **after** the 0.5.4 release, i.e. at the 0.5.5 release? `./skbio/alignment/_pairwise.py:@deprecated(as_of="0.4.0", until="0.5.4",`
Next, I will build docs, etc.
FYI after 0.5.4 release, I will open a new PR updating the `__init__.py` version string to `0.5.4-dev` and adding a new `0.5.4-dev` section to the changelog.
> MAINT: Prepare skbio 0.5.4 release: update version strings and changelog

- CHANGELOG.md
- skbio/__init__.py
> Update version string and changelog to 0.5.4-dev

- skbio/sequence/_sequence.py
> DOC: fixing numpy repr

- skbio/alignment/tests/test_tabular_msa.py
> MAINT: reorder dict entries for py36 support

- skbio/io/format/blast6.py
- skbio/io/format/blast7.py
> blastoff 🚀

- skbio/stats/ordination/_canonical_correspondence_analysis.py
- skbio/stats/ordination/_redundancy_analysis.py
> Ordination warnings

- skbio/stats/distance/_mantel.py
Fixes a DeprecationWarning that crops up a lot in the tests.
> Use scipy.special.comb instead of scipy.misc.comb

- skbio/alignment/_tabular_msa.py
- skbio/alignment/tests/test_tabular_msa.py
- skbio/sequence/_sequence.py
> Sprint again

- CHANGELOG.md
- Makefile
- skbio/io/format/blast6.py
- skbio/io/format/blast7.py
- skbio/io/format/tests/test_fasta.py
- skbio/io/format/tests/test_stockholm.py
- skbio/metadata/tests/test_interval.py
- skbio/sequence/tests/test_sequence.py
- skbio/tree/tests/test_tree.py
Note that this should be the final changelog before the scikit-bio 0.5.5 release.  @thermokarst @ebolyen @wasade @ElDeveloper
> skbio version 0.5.5 changelog

- skbio/__init__.py
- skbio/alignment/_pairwise.py
- skbio/stats/composition.py
> Updating version strings for release

- CHANGELOG.md
- skbio/__init__.py
Updates version strings and the changelog
> REL: Post-release cleanup

- .gitignore
- CHANGELOG.md
- skbio/sequence/_grammared_sequence.py
- skbio/sequence/tests/test_grammared_sequence.py
---
This PR implements #1431. Sorry for the delay.
This is my first time contributing and I would love to continue so please let me know if everything checks out!
> Add capture group option for `GrammaredSequence.to_regex` fixes #1431

- CHANGELOG.md
- skbio/alignment/_pairwise.py
- skbio/diversity/_driver.py
- skbio/diversity/_util.py
- skbio/diversity/tests/test_util.py
- skbio/io/format/tests/test_ordination.py
- skbio/io/format/tests/test_stockholm.py
- skbio/sequence/_grammared_sequence.py
#1521
*  [x] I have read the guidelines in [CONTRIBUTING.md](https://github.com/biocore/scikit-bio/blob/master/CONTRIBUTING.md).
> [quick fix]Support for pd DataFrame in beta_diversity

- CHANGELOG.md
Just noticed the changelog had a misplaced note from #1651.
------------------------
> DOC: Minor update to Changelog

- skbio/stats/distance/tests/test_mantel.py
- skbio/stats/evolve/_hommola.py
- skbio/stats/power.py
Build fixes for issues stemming from 0.25.0 and scipy 1.3.0.
> WIP: Build fixes for pandas 0.25.0 and scipy 1.3.0

- README.rst
It seems to me that we don't need to install **numpy** separately, because it would be installed automatically based on the dependencies listed in **setup.py**.
> update README.rst (don't need to install numpy separately)

- CHANGELOG.md
> DOC: changelog mention was in the wrong location

- CHANGELOG.md
- skbio/sequence/_protein.py
> add U, O, and J amino acid codes

- CHANGELOG.md
- skbio/stats/distance/tests/test_anosim.py
- skbio/util/_testing.py
> fix pandas.testing import for pandas 1.0.0

- Makefile
- skbio/alignment/_tabular_msa.py
- skbio/stats/distance/_base.py
- skbio/stats/distance/_bioenv.py
- skbio/stats/distance/_permdisp.py
- skbio/stats/gradient.py
- skbio/stats/ordination/_ordination_results.py
This is to further fix the errors caused by Pandas 1.0.1. 
Fix #1692  
* [Y ] I have read the guidelines in [CONTRIBUTING.md](https://github.com/biocore/scikit-bio/blob/master/CONTRIBUTING.md).
* [Y ] I have documented all public-facing changes in [CHANGELOG.md](https://github.com/biocore/scikit-bio/blob/master/CHANGELOG.md).
* [N ] **This pull request includes code, documentation, or other content derived from external source(s).** If this is the case, ensure the external source's license is compatible with scikit-bio's [license](https://github.com/biocore/scikit-bio/blob/master/COPYING.txt). Include the license in the `licenses` directory and add a comment in the code giving proper attribution. Ensure any other requirements set forth by the …
> Fix errors caused by pandas 1.0.1

- CHANGELOG.md
- skbio/__init__.py
---
`@experimental`s in dev were already pointing to 0.5.6, which is why there are no changes reflected in this changeset.
> MAINT: Prep for 0.5.6 release

- CHANGELOG.md
- setup.py
Following from #1690 this updates the `hdmedians` dependency to avoid an issue where numpy had to be manually installed. This should fix the rest of #1671 
> Update hdmedians to >= 0.14.1

- CHANGELOG.md
- skbio/stats/distance/_base.py
- skbio/stats/distance/_cutils.c
- skbio/stats/distance/_cutils.pyx
- skbio/stats/distance/_permanova.py
Refactor permanova. Now about 100x faster.
Remove the large intermediate buffers and implement the time consuming part in cython.
Issue #1767 
> Issue 1767 - Speed up permanova

- CHANGELOG.md
- skbio/stats/distance/_base.py
- skbio/stats/distance/_permanova.py
- skbio/stats/distance/_permdisp.py
- skbio/stats/distance/tests/test_permdisp.py
Add support for OrdinationResults input for permdisp.
Issue #1771
> Add support for OrdinationResults input for permdisp

- skbio/stats/distance/_mantel.py
- skbio/stats/distance/tests/test_mantel.py
---
I _believe_ this should fix the issues noted in #1785
> BUG: Fix mantel bootstrap on some archs

- setup.py
Signed-off-by: Andrew Robbins <andrew@robbinsa.me>
> Add MSVC OpenMP compiler flag for SIMDe on Windows (close #1796)

- CHANGELOG.md
- skbio/stats/composition.py
Addresses issue #1741. This fixes the conflict in #1743
> Issue 1741

- CHANGELOG.md
- setup.py
- skbio/__init__.py
Remark on the 0.5.7 release, once green will merge and tag release
> REL: denote 0.5.7 release

- README.rst
> add maintenance mode note to README

- CHANGELOG.md
- doc/source/conf.py
- skbio/alignment/_tabular_msa.py
- skbio/alignment/tests/test_tabular_msa.py
- skbio/diversity/__init__.py
- skbio/io/format/blast6.py
- skbio/io/format/blast7.py
- skbio/metadata/_testing.py
- skbio/sequence/tests/test_sequence.py
- skbio/stats/gradient.py
- skbio/stats/tests/test_gradient.py
> WIP: pandas >= 2.0 support

- simde-sse2.h
Reissue of #1854 to trigger tests
> Simde v0.7.6

- CHANGELOG.md
- skbio/__init__.py
> REL: 0.5.9

- skbio/diversity/__init__.py
Issue #1872
It's a one character change to a doc page. I'm not sure it warrants a change log entry.
> Corrected typo in skbio.diversity docs

- README.rst
> adding citation

- CHANGELOG.md
- skbio/sequence/_dna.py
- skbio/sequence/_grammared_sequence.py
- skbio/sequence/_protein.py
- skbio/sequence/_rna.py
- skbio/sequence/tests/test_dna.py
- skbio/sequence/tests/test_protein.py
- skbio/sequence/tests/test_rna.py
Addressing issues #1637 and #1882 . Through discussion, we think that the previous method may be over conservative. Enabling subclassing can facilitate secondary development which is desired by the community.
> Enabled subclassing of sequence classes

- skbio/diversity/alpha/_pd.py
@qiyunzhu @mortonjt 
Simple fix to correctly render the last formula in the `phydiv` documentation. See PR #1893 for more details.
* [ X] I have read the guidelines in [CONTRIBUTING.md](https://github.com/biocore/scikit-bio/blob/master/.github/CONTRIBUTING.md).
* [ X] I have documented all public-facing changes in [CHANGELOG.md](https://github.com/biocore/scikit-bio/blob/master/CHANGELOG.md).
> Fixed formula rendering in phydiv documentation

- skbio/diversity/alpha/_base.py
- skbio/diversity/alpha/tests/test_base.py
This is an ongoing effort but I think I need to make a checkpoint here. Basically I was reviewing all alpha diversity metrics currently implemented in scikit-bio. What I did include:
- Added definitions, common denotions, original publications, and any useful notes on each metric.
- Dealt with edge cases such that the result of an empty sample will be zero, instead of nan or zero division warning.
- Replaced "OTU" with "species" as the former is bit historical and specific.
Further improvements will follow, but we should move forward from here.
> Improving alpha diversity metrics

- README.rst
Per our discussion, the full announcement will be online in January. The current PR only removes the old announcement "scikit-bio is currently in maintenance mode".
@wasade Will the website be updated as soon as we edit the README file, or should we manually trigger something?
> Removed maintenance mode announcement

- .github/CONTRIBUTING.md
- .github/PULL_REQUEST_TEMPLATE.md
- CHANGELOG.md
- README.rst
- RELEASE.md
- REVIEWING.md
- doc/README.md
- doc/source/_templates/layout.html
- doc/source/development/coding_guidelines.rst
- doc/source/development/new_module.rst
- setup.py
- skbio/__init__.py
- skbio/alignment/_pairwise.py
- skbio/alignment/_tabular_msa.py
- skbio/io/format/_base.py
- skbio/io/format/embl.py
- skbio/io/format/fasta.py
- skbio/io/format/tests/test_embl.py
- skbio/io/registry.py
- skbio/sequence/tests/test_sequence.py
- skbio/stats/distance/tests/test_permanova.py
- skbio/stats/distance/tests/test_permdisp.py
Also updated the instruction for building documentation ([doc/README.md](https://github.com/scikit-bio/scikit-bio/tree/master/doc)). Previously it was:
```bash
pip install 'Sphinx<=3.0' sphinx-bootstrap-theme
```
Now it becomes:
```bash
conda install sphinx sphinx_bootstrap_theme
```
Tested and working. The current versions are sphinx==7.2.6 and sphinx_bootstrap_theme==0.8.1. In fact, the previous official skbio website was built by Sphinx 7.1.2. Therefore the <=3.0 limit was already obsolete.
> Updated GitHub URLs from "biocore" to "scikit-bio"

- skbio/tree/_tree.py
This PR is the first of several which will address errors that have been found by running the [Ruff](https://docs.astral.sh/ruff/) linter on our codebase. This error is a simple renaming of a variable from lowercase 'l' to uppercase 'L' in order to avoid potential font-dependent ambiguities with 'I' (capital i), '1', or 'l' (lowercase L).
The errors identified by Ruff's linter can be seen below:
After these errors have been resolved, keep an eye out for a WIP PR regarding the integration of Ruff's formatter and linter into skbio. This future WIP PR may serve as a discussion platform for the development team regarding the specifics of integrating Ruff into skbio.
**Note:** [REVIEWING.md](https://github.com/scikit-bio/scikit-bio/blob/master/REVIEWING. …
> Fixed ambiguous variable name

- CHANGELOG.md
- skbio/diversity/alpha/_base.py
This PR fixes the broken link pointed out by @colinvwood in issue #1923. 
**Note:** [REVIEWING.md](https://github.com/scikit-bio/scikit-bio/blob/master/REVIEWING.md) may also be helpful to see some of the things code reviewers will be verifying when reviewing your pull request.
> Fix broken link for Simpson's evenness

- .github/CONTRIBUTING.md
- .pre-commit-config.yaml
This PR adds basic documentation for the use of Ruff via pre-commit hooks. As the development team is intending to refactor and update `skbio`'s documentation in the near future, this documentation has simply been added to the end of the `CONTRIBUTING.md` file. 
Additionally, the `--fix` option has been removed from the linting step of the pre-commit hook. The logic here is that having the pre-commit hook make automated linting changes may become confusing. To make any safe changes automatically, the developer may run:
```python
ruff check --fix <path/to/file.py>
```
Otherwise, changes suggested by the linter will be made manually. 
**Note:** [REVIEWING.md](https://github.com/scikit-bio/scikit-bio/blob/master/REVIEWING.md) may also be helpful to …
> Ruff documentation

- .github/CONTRIBUTING.md
- .github/workflows/ci.yml
- .pre-commit-config.yaml
- CHANGELOG.md
- setup.py
- skbio/diversity/alpha/_base.py
- skbio/io/tests/test_util.py
This PR is a test to see if the garbage collection (`gc`) solution proposed by @actapia (See #1897) can function with Python 3.12. Another solution by @actapia is in #1928.
**Note:** [REVIEWING.md](https://github.com/scikit-bio/scikit-bio/blob/master/REVIEWING.md) may also be helpful to see some of the things code reviewers will be verifying when reviewing your pull request.
> Garbage collection for Gzip functionality in Python 3.12

- pyproject.toml
Simple PR to change single quotes to double quotes for Ruff configuration file.
> Fix single quotes

- skbio/tree/_nj.py
Cleaned up docstrings and updated reference material on neighbor joining and phylogenetic inference.
> Updated documentation for nj

- skbio/stats/composition.py
- Fixed the documentation for  `dirmult_ttest`. 
- Changed the return values to correspond with the code. 
- Fixed linting issues.
[* ] I have read the [contribution guidelines](https://scikit.bio/contribute.html).
[* ] I have documented all public-facing changes in the [changelog](https://github.com/scikit-bio/scikit-bio/blob/main/CHANGELOG.md).
[* ] **This pull request includes code, documentation, or other content derived from external source(s).** If this is the case, ensure the external source's license is compatible with scikit-bio's [license](https://github.com/scikit-bio/scikit-bio/blob/main/LICENSE.txt). Include the license in the `licenses` directory and add a comment in the code giving proper attribution. Ensure any other requirements …
> Dirmult ttest documentation 

- CHANGELOG.md
- skbio/__init__.py
- skbio/diversity/_driver.py
- skbio/diversity/_util.py
- skbio/diversity/tests/test_driver.py
- skbio/diversity/tests/test_util.py
- skbio/feature_table/__init__.py
- skbio/feature_table/_base.py
- skbio/io/__init__.py
- skbio/io/_exception.py
- skbio/io/_fileobject.py
- skbio/io/format/biom.py
- skbio/io/format/tests/test_biom.py
> ENH: biom-format IO support

- skbio/diversity/_driver.py
Missed a few docstring changes in #1984 
> DOC: Table mention in drivers

- skbio/alignment/_pairwise.py
- skbio/diversity/_driver.py
- skbio/diversity/alpha/_base.py
- skbio/sequence/_grammared_sequence.py
- skbio/util/_warning.py
This PR introduces a function to avoid repetitive coding for warning of deprecated function status. See #1969 for more details.
> Create deprecation warning function

- skbio/metadata/_metadata.py
I realized that there could be some use cases that would wrongly call qiime2 imports and attempt to create qiime2 artifacts.  All such instances have been removed.
> Removing all instances of artifact

- skbio/io/__init__.py
- skbio/io/format/biom.py
This PR implements a simple solution to the problem illustrated in issue #1990. It also includes some formatting changes to the file made by ruff.
> Use os.remove to remove generated .biom file

- .github/workflows/release.yml
- CHANGELOG.md
- README.rst
- skbio/__init__.py
- web/index.rst
- web/versions.json
This will ready release 0.6.0. After merging, the documentation website will shut down transiently, until the release tag is created.
> Release 0.6.0

- skbio/__init__.py
- web/index.rst
- web/suburl.py
This PR changes the development version to 0.6.1-dev (following the [instruction](https://scikit.bio/devdoc/release.html#post-release-cleanup)), and changes the default documentation to "latest" instead of "dev".
The version number "0.6.1" is a placeholder. It can be "0.7.0" if the next release is significant.
Note: [This document](https://scikit.bio/devdoc/review.html) may also be helpful to see some of the things code reviewers will be verifying …
> Upped version to 0.6.1-dev

- ci/aarch64.requirements.txt
- ci/conda_requirements.txt
- setup.py
Simple PR to remove all hdmedians requirements and imports.
> Remove all hdmedians imports and requirements

- .github/workflows/ci.yml
> Update CI to apply the build matrix Python version on testing

- skbio/alignment/tests/test_tabular_msa.py
- skbio/io/format/tests/test_binary_dm.py
- skbio/io/tests/test_registry.py
- skbio/io/tests/test_util.py
- skbio/metadata/_testing.py
- skbio/metadata/tests/test_missing.py
- skbio/sequence/tests/test_grammared_sequence.py
- skbio/sequence/tests/test_sequence.py
- skbio/stats/_subsample.py
This PR solves many of the issues preventing scikit-bio from being used on windows machines. However, it does not solve all of the issues. This PR handles the more trivial problems, including basic data type issues and line ending issues. More complex problems will be handled in future PRs.
Additionally, Windows has not been added to our CI workflow at this point. This will happen when the more complex issues are handled. 
Note: [This …
> Fix trivial Windows support issues

- web/contribute.rst
> fix typo in link to Github repository

- setup.py
- skbio/embedding/__init__.py
- skbio/embedding/_embedding.py
- skbio/embedding/_protein.py
- skbio/embedding/tests/__init__.py
- skbio/embedding/tests/test_embedding.py
- skbio/embedding/tests/test_protein.py
- skbio/io/format/tests/test_embed.py
This PR did some minor edits to the embedding functionality. Unit test coverage is upped. Entries were added to documentation. Wording in documentation and error messages were adjusted. Unused imports were removed. Unit test methods were adjusted. Some minor issues (like redundant copy of np.array, unwanted file writing during unit test) were fixed.
Note: [This document](https://scikit.bio/devdoc/review.html) may also be helpful to see some of the …
> Minor edits of embedding

- CHANGELOG.md
- skbio/tree/_tree.py
- skbio/tree/tests/test_tree.py
> Added support for dict and dataframe for `TreeNode.from_taxonomy`

- CHANGELOG.md
- README.rst
- doc/source/_static/css/style.css
- doc/source/conf.py
- doc/source/index.rst
- skbio/__init__.py
- skbio/diversity/alpha/_base.py
- web/_static/css/style.css
- web/conf.py
- web/index.rst
- web/install.rst
- web/learn.rst
- web/versions.json
This PR will release scikit-bio 0.6.1. Below is a draft release note.
***
We are excited to announce scikit-bio 0.6.1!
This release introduces significant enhancements and features, including the launch of a new website, the addition of new modules, classes and algorithms, and support for the latest versions of Python and SciPy. This release also includes various optimizations, bug fixes, and documentation improvements, making it a substantial upgrade for users and developers alike.
**Release highlights:**
- Added module `skbio.embedding` to provide support for storing and manipulating embeddings for biological objects, such as protein embeddings outputted from protein language models (pLMs).
- Added an efficient sequence alignment path data structure `AlignPath` to provide a uniform …
> Release 0.6.1

- CHANGELOG.md
- skbio/__init__.py
- skbio/diversity/alpha/tests/test_base.py
> upped verison to 0.6.2-dev

- skbio/tree/_tree.py
This PR attempts to fix a Ruff linting issue recently emerged (on unchanged code).
> Trying to fix Ruff E721

- .github/workflows/ci.yml
- CHANGELOG.md
- setup.py
This PR will update the CI and other necessary elements to enable the use of skbio on Windows machines.
> WIP:  Full windows support

- .pre-commit-config.yaml
Simple PR to update the Ruff version used in the pre-commit hooks.
> Update Ruff version

- .github/workflows/ci.yml
Codecov disappeared from PRs. Don't know why. This PR is trying to reactivate it.
> Upping GitHub Actions versions

- CHANGELOG.md
- README.rst
- skbio/__init__.py
- skbio/tree/__init__.py
- web/index.rst
- web/versions.json
Draft release notes:
0.6.2
scikit-bio 0.6.2
We are excited to announce scikit-bio 0.6.2!
**Release highlights:**
- scikit-bio now has full support for Microsoft Windows.
- Significantly improved the efficiency and functionality of `TreeNode` for storing and manipulating phylogenetic trees.
- Implemented nearest neighbor interchange (NNI) (`nni`) for phylogenetic tree rearrangement.
- Implemented alpha diversity metrics: Hill number (`hill`), Renyi entropy (`renyi`) and Tsallis entropy (`tsallis`).
- Enabled ID renaming for classes `DissimilarityMatrix` and `OrdinationResults`.
Review the [changelog](https://github.com/biocore/scikit-bio/blob/main/CHANGELOG.md#version-062) for a complete list of the changes. Browse the [documentation](https://scikit.bio/docs/0.6.2/index.html) to learn …
> Releasing 0.6.2

- CHANGELOG.md
- skbio/__init__.py
- web/install.rst
Also temporarily muted the test command as it will throw segmentation facult in some users' computers.
> Bumped version to 0.6.3-dev

- CHANGELOG.md
- skbio/tree/_upgma.py
- skbio/tree/tests/test_upgma.py
SciPy's functions 'average' and 'weighted' implement UPGMA and WPGMA, respectively. These functions are included into scikit-bio while producing a TreeNode object instead of the linkage matrix produced by SciPy.
This is WIP. Remaining tasks are:
-unit testing
-changelog
> Wrapping SciPy's UPGMA and WPGMA functions (WIP)

- .github/workflows/ci.yml
- .github/workflows/release.yml
- ci/requirements.doc.txt
- doc/editmap.py
- doc/source/conf.py
- web/.exclude
- web/conf.py
This PR creates a sitemap for indexing webpages, such that search engines can pick them up.
> Search engine optimization

- skbio/diversity/_util.py
- skbio/diversity/alpha/_base.py
- skbio/diversity/alpha/_pd.py
> Improved documentation of phylogenetic diversity

- web/versions.json
> Dropped redundant versions

- doc/source/_templates/TreeNode.rst
- skbio/sequence/_genetic_code.py
- skbio/tree/__init__.py
- skbio/tree/_tree.py
> Improved documentation of TreeNode

- skbio/tree/_tree.py
- skbio/tree/tests/test_tree.py
Does not affect the result, but is safer.
***
> TreeNode.siblings by identity

- CHANGELOG.md
- doc/source/_templates/TreeNode.rst
- skbio/tree/_tree.py
- skbio/tree/tests/test_tree.py
> Added `TreeNode.is_bifurcating`

- CHANGELOG.md
- skbio/stats/composition.py
- skbio/tree/_tree.py
- skbio/tree/tests/test_tree.py
> Improved random shuffling functions of tree

- CHANGELOG.md
- skbio/diversity/alpha/_lladser.py
- skbio/stats/_subsample.py
- skbio/stats/power.py
- skbio/stats/tests/test_power.py
- skbio/stats/tests/test_subsample.py
Partially addressing #2096 .
***
> Updating numpy random generator

- CHANGELOG.md
- skbio/diversity/alpha/tests/test_lladser.py
- skbio/stats/distance/_anosim.py
- skbio/stats/distance/_base.py
- skbio/stats/distance/_mantel.py
- skbio/stats/distance/_permanova.py
- skbio/stats/distance/_permdisp.py
- skbio/stats/distance/tests/data/pwmantel_exp_results_minimal.txt
- skbio/stats/distance/tests/data/pwmantel_exp_results_minimal_with_labels.txt
- skbio/stats/distance/tests/data/pwmantel_exp_results_reordered_distance_matrices.txt
- skbio/stats/distance/tests/test_anosim.py
- skbio/stats/distance/tests/test_base.py
- skbio/stats/distance/tests/test_mantel.py
- skbio/stats/distance/tests/test_permanova.py
- skbio/stats/distance/tests/test_permdisp.py
- skbio/stats/evolve/_hommola.py
- skbio/stats/evolve/tests/test_hommola.py
- skbio/stats/ordination/_principal_coordinate_analysis.py
This is part of the effort to adopt the new random generator. Note that some unit tests have to been changed to reflect the new results.
***
> Added random generator support for distance tests

- CHANGELOG.md
- skbio/diversity/alpha/_lladser.py
- skbio/stats/_subsample.py
- skbio/stats/composition.py
- skbio/stats/power.py
- skbio/util/_misc.py
- skbio/util/tests/test_misc.py
This PR completely addresses #2096, #2124, and other discussions. @mortonjt @wasade 
***
> Added legacy random generator support

- CHANGELOG.md
- doc/source/_templates/TreeNode.rst
- skbio/tree/_tree.py
- skbio/tree/tests/test_tree.py
This PR fixed a bug in the [lowest common ancestor](https://en.wikipedia.org/wiki/Lowest_common_ancestor) algorithm of the tree structure. If one of the input nodes is ancestral to other nodes, the `lca` method will return the parent of that node, which is incorrect, instead of the node itself. For example:
```python
>>> tree = TreeNode.read(['(((a,b)c,d)e,(f,(g,h)i)j)k;'])
>>> print(tree.ascii_art())
/-a
/c-------|
/e-------|          \-b
|         |
-k-------|          \-d
|
|          /-f
\j-------|
|          /-g
\i-------|
\-h
>>> tree.lca(['a', 'b', 'c']).name  # the correct result should be 'c'
'e'
```
This behavior is unlikely to be intensional, because supplying a single node will return the node itself.
```python
>>> tree.lca(['c']).name
'c'
```
This PR fixed this bug, and also …
> Bug-fixed and optimized lowest common ancestor

- skbio/stats/composition.py
Organized functions under `skbio.stats.composition`. Like this:
***
> Categorized composition functions

- simde-sse2.h
* ~~This pull request does not include code, documentation, or other content derived from external source(s)~~.
> MNT: upgrade SIMDe to v0.8.2

- CHANGELOG.md
- skbio/tree/_tree.py
- skbio/tree/tests/test_tree.py
- skbio/util/__init__.py
- skbio/util/_warning.py
Significantly improved the performance of `TreeNode.tip_tip_distances`.
This method generates a distance matrix of the sum of branch lengths connecting each pair of tips in a tree. It is a prerequisite for calculating some tree-to-tree distance metrics, such as path-length distance. The previous code was fairly efficient. This PR further improved the performance by maximizing the use of NumPy vectorization, making tip index ranges continuous (therefore becoming slices), and removing the need for an intermediate square matrix of the total number of tips in the tree, which is a major bottleneck, especially when only a subset of the tips are to be calculated.
Test on a tree with 10,575 tips:
- All tips
- Before: 12.2s
- After: 318 ms
- 5,000 randomly selected tips
- Before: 3.59 s
- After: …
> Optimized tip_tip_distances

- skbio/sequence/_protein.py
- skbio/sequence/_sequence.py
- skbio/stats/composition.py
- skbio/stats/distance/tests/test_mantel.py
- skbio/stats/distance/tests/test_permdisp.py
- skbio/stats/ordination/_redundancy_analysis.py
- skbio/stats/ordination/tests/test_redundancy_analysis.py
- skbio/stats/tests/test_composition.py
- skbio/util/_warning.py
> Resolved some warnings

- CHANGELOG.md
- skbio/stats/distance/_permdisp.py
- skbio/stats/distance/tests/test_permdisp.py
- skbio/stats/ordination/_principal_coordinate_analysis.py
- skbio/stats/ordination/tests/test_principal_coordinate_analysis.py
> Relaxed pcoa negative eigenvalue warning

- skbio/io/__init__.py
This PR aims to improve the documentation for the `io` module. The main focus is to put links to relevant resources at the top of the first page of the `io` module documentation. Elaboration on certain topics and links to other places in the documentation for very common use cases (reading multi-line FASTA files for example) are also included.
@qiyunzhu and I have been discussing scikit-bio's documentation more broadly, and feel that it might be useful in the future to separate the `Tutorial` sections that are found in most module's documentation and put them into a `User Guide` section on the website. This would indeed be a major overhaul from the current documentation, where we have the API reference and examples all on one page for most modules. My opinion is that separating "tutorial" …
> Improvements to skbio.io documentation

- .github/workflows/ci.yml
- .github/workflows/release.yml
- CHANGELOG.md
- setup.py
- web/devdoc/release.rst
... since it has reached the end-of-life (EOL).
> Dropped support for Python 3.8

- README.rst
- doc/source/conf.py
- web/conf.py
... as we are reaching the end of year 2024.
> Removed "revitalizing scikit-bio in 2024" announcement

- CHANGELOG.md
- skbio/io/format/fasta.py
- skbio/io/format/tests/data/fasta_multi_seq_spaces
- skbio/io/format/tests/test_fasta.py
- skbio/sequence/_grammared_sequence.py
- skbio/sequence/_sequence.py
- skbio/sequence/tests/test_sequence.py
This PR addresses issue #2148. ~~It is WIP for now because of some unexpected behavior in one of the doctests and possibly adding more unit tests. However,~~ the current code should be functional.
> Add remove_spaces to handle sequences with spaces

- CHANGELOG.md
- doc/source/_templates/TreeNode.rst
- skbio/tree/_tree.py
- skbio/tree/tests/test_tree.py
> Added height and depth calculations to `TreeNode`.

- skbio/stats/ordination/_correspondence_analysis.py
This PR updates documentation for the scaling parameter in correspondence analysis for stats ordination to improve readability. The previous documentation was overly detailed, containing excessive information that has now been moved to the Notes section for users.
> ca function documentation update for scaling parameter

- doc/source/_templates/TreeNode.rst
- doc/source/conf.py
- skbio/io/__init__.py
- skbio/io/tests/test_registry.py
- skbio/tree/__init__.py
- skbio/tree/_me.py
- skbio/tree/_nj.py
- skbio/tree/_tree.py
- skbio/tree/tests/test_me.py
- skbio/tree/tests/test_nj.py
> updated tree tutorial

- CHANGELOG.md
- skbio/__init__.py
> Bumped version to 0.6.4-dev

- CHANGELOG.md
- skbio/io/__init__.py
This adds documentation for the `verify=False` solution to #2017. 
> Document `verify=False` option for stdin support

- skbio/table/__init__.py
- skbio/table/_augment.py
- skbio/table/tests/test_augment.py
This PR is trying to integrate the phylomix into the scikit-bio, this is an initial version. We can further discuss the desired output and supported functionalities
> Integrate Phylomix into Scikit-bio

- skbio/diversity/alpha/_lladser.py
- skbio/diversity/alpha/tests/test_chao1.py
- skbio/diversity/alpha/tests/test_lladser.py
- skbio/diversity/alpha/tests/test_pd.py
- skbio/diversity/beta/tests/test_unifrac.py
- skbio/stats/distance/_mantel.py
- skbio/stats/distance/_permdisp.py
- skbio/stats/distance/_utils.py
- skbio/stats/distance/tests/test_mantel.py
- skbio/stats/distance/tests/test_permanova.py
- skbio/stats/distance/tests/test_permdisp.py
- skbio/stats/distance/tests/test_util.py
> Increasing unit-test coverage

- CHANGELOG.md
- skbio/stats/distance/_base.py
> Add parameter documentation to `DistanceMatrix`

- skbio/io/format/ordination.py
- skbio/stats/ordination/_canonical_correspondence_analysis.py
- skbio/stats/ordination/_correspondence_analysis.py
- skbio/stats/ordination/_ordination_results.py
- skbio/stats/ordination/_principal_coordinate_analysis.py
- skbio/stats/ordination/_redundancy_analysis.py
- skbio/util/__init__.py
- skbio/util/_types.py
- skbio/util/config/__init__.py
- skbio/util/config/_config.py
- skbio/util/config/_dispatcher.py
- skbio/util/config/_optionals.py
- skbio/util/config/_types.py
- skbio/util/tests/test_dispatcher.py
This PR improves the documentation for the tabular data dispatch system introduced in #2187. 
Notably, this PR introduces the `DataTable` type, which is a `typing.Union` of the appropriate types from numpy, pandas, polars, BIOM, and anndata.
> Improve documentation for tabular data handling

- skbio/stats/ordination/_ordination_results.py
- skbio/stats/ordination/tests/test_ordination_results.py
> Added 2D functionality + unit tests

- CHANGELOG.md
- skbio/stats/distance/_base.py
- skbio/stats/ordination/_ordination_results.py
This PR increases the visibility of the `plot` method for the `OrdinationResults`, `DistanceMatrix`, and `DissimilarityMatrix` objects. It also improves formatting in the `stats.distance._base.py` file.
> Improve documentation for existing plotting methods

- CHANGELOG.md
- doc/source/conf.py
- skbio/alignment/_path.py
- skbio/alignment/_tabular_msa.py
- skbio/io/format/embed.py
- skbio/metadata/_interval.py
- skbio/metadata/_metadata.py
- skbio/sequence/_sequence.py
- skbio/stats/distance/_anosim.py
- skbio/stats/distance/_base.py
- skbio/stats/distance/tests/test_base.py
- skbio/stats/gradient.py
- skbio/util/_decorator.py
- skbio/util/_types.py
This PR represents the initial efforts at adding type hinting to scikit-bio's codebase. The advantages of type annotations are numerous and include finding bugs more quickly, improved auto-completion, and checking correctness in downstream applications.
This PR adds type hinting to `stats.distance._base` and `stats.distance._anosim` as well as a few other files which contain code which affects the `distance` module. Further additions of type annotations to the `stats.distance` module will occur in future PRs.
Additionally, type errors from other modules where type annotations were already present were ignored, with the intention of revisiting these issues when we have more of the code base typed.
- **It is your responsibility to disclose** code, …
> Add type hinting to the `stats.distance` module

- .pre-commit-config.yaml
Simple PR to update ruff to the latest version for the pre-commit hooks.
> Update ruff version used in pre-commit hooks

- skbio/alignment/_path.py
> Documented the conversion between scikit-bio and Biopython alignments

- skbio/alignment/_path.py
> Enriched documentation of PairAlignPath, with CIGAR code translation

- skbio/alignment/tests/test_pair.py
- skbio/tree/_me.py
> Just fixing some typos

- web/install.rst
- web/learn.rst
This PR fixes the broken links on the `Install` and `Learn` pages of scikit-bio's website. There may be other broken links, so I'd like to leave this PR open for a bit to give us time to find and fix any others.
@qiyunzhu @mortonjt @wasade If you are aware of or come across any other broken links in the documentation let me know and I can fix them and add it to this PR.
Note: [This document](https://scikit.bio/devdoc/review.html) may also be helpful …
> Fix broken link(s) in documentation.

- skbio/sequence/__init__.py
- skbio/sequence/_genetic_code.py
- skbio/sequence/_sequence.py
> Enriched the tutorial of `skbio.sequence`

- .github/workflows/wheels.yml
Fixes an error in `wheels.yml` which prevented the workflow from running at all.
> Fix `wheels.yml`

- skbio/table/_augment.py
This PR addresses comments received from @liaodisen . 
> Minor fixes for augmentation module

- .codecov.yml
- .coveragerc
- skbio/binaries/_distance.py
- skbio/binaries/_ordination.py
- web/install.rst
This PR updates the `Install` page of scikit-bio's website to include newly developed options such as installing from pre-compiled wheels, and installing the new scikit-bio-binaries package. It also removes some deprecated functionality, notably `python setup.py install`.
> Rewrite install page for website

- CHANGELOG.md
- doc/source/conf.py
- doc/source/reference/table_like.rst
- skbio/alignment/_pair.py
- skbio/alignment/_path.py
- skbio/alignment/_score.py
- skbio/binaries/_ordination.py
- skbio/sequence/_sequence.py
- skbio/sequence/_substitution.py
- skbio/stats/composition.py
- skbio/stats/distance/tests/test_permdisp.py
- skbio/stats/ordination/_principal_coordinate_analysis.py
- skbio/stats/ordination/tests/test_principal_coordinate_analysis.py
- skbio/stats/tests/test_composition.py
- skbio/stats/tests/test_ndarray.py
- skbio/table/_tabular.py
- skbio/table/tests/test_tabular.py
- skbio/util/_array.py
- skbio/util/_gpu.py
- skbio/util/_typing.py
- skbio/util/tests/test_array.py
- web/index.rst
> Improving documentation and code for table-like formats

- CHANGELOG.md
- README.rst
- doc/source/index.rst
- skbio/__init__.py
- skbio/stats/composition.py
- web/index.rst
- web/versions.json
> Bumped version to 0.7.0

- CHANGELOG.md
- skbio/__init__.py
- web/conf.py
- web/index.rst
> Bumped version to 0.7.1-dev

- pyproject.toml
When [building the package](https://github.com/conda-forge/scikit-bio-feedstock/pull/64/checks) at conda-forge, it said:
```
/home/conda/feedstock_root/build_artifacts/scikit-bio_1752735797405/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_/lib/python3.10/site-packages/setuptools/config/_apply_pyprojecttoml.py:61: SetuptoolsDeprecationWarning: License classifiers are deprecated.
!!
********************************************************************************
Please consider removing the following classifiers in favor of a SPDX license expression:
License :: OSI Approved :: BSD License
See https://packaging.python.org/en/latest/guides/writing-pyproje …
```
> Updated the format of license in pyproject.toml

- skbio/io/format/binary_dm.py
- skbio/io/format/tests/test_binary_dm.py
> Fix binary_dm reader

- CHANGELOG.md
- skbio/alignment/_pair.py
- skbio/alignment/tests/test_pair.py
This PR fixed the bug reported in #2279 . @gregcaporaso 
> Addressing issue 2279

- CHANGELOG.md
- skbio/io/format/binary_dm.py
- skbio/io/format/tests/test_binary_dm.py
> Fix binary_dm writer and add support for version 2020.12

- skbio/diversity/alpha/tests/test_base.py
- skbio/diversity/alpha/tests/test_chao1.py
- skbio/diversity/alpha/tests/test_gini.py
- skbio/table/tests/test_augment.py
- skbio/tree/tests/test_compare.py
- skbio/tree/tests/test_me.py
> Replacing deprecated numpy function

- skbio/stats/distance/_permanova.py
> Minor improvement to clarity of R^2 formula in stats.distance.permanova
